---
title: "A phone designed not to be used: what would it take to build one?"
description: "What can be done about phone addiction? Would it be feasible to
create a new phone brand? How could that even be done? I have more questions
than answers, but I'm hoping this series helps a bit."
author: "Mario Ortiz Manero"
images: ["TODO"]
tags: ["tech", "phone addiction", "eink", "entrepreneurship", "calm companies",
"dumbphones", "phone manufacturing"]
series: ["dont-use-this-phone"]
date: 2024-06-01
GHissueID: TODO
draft: true
---

TODO: fill out description in series/dont-use-this-phone/_index.md

What if there was a company selling phones that, against all odds, optimized how
_little_ they were used? Given that every company is trying to get you hooked
into their app, there's so much that can be done here.

We have "https://en.wikipedia.org/wiki/Feature_phone[dumbphones]", for example.
These are phones whose functionality is intentionally locked down, with the
purest examples only supporting calls and SMS. On the other side of the
spectrum, we have smartphones. It wouldn't be far-fetched to say that most
people owning one use it more than they'd like.

I've seen people around me switching to a dumbphone. It's not a bad idea; it
helps them reduce anxiety in the short term. But in the longer term, it turns
out to be impossible. Firstly, because some apps like WhatsApp or Lyft can be
indispensable for many. And secondly, because using most apps within reasonable
means are an improvement in quality of life. A GPS can be of immense help
getting around, or even Netflix can be a great ally to fight boredom in a plane.

And as a big fan of second-hand stuff, I'd rather give an old Motorola a second
life than bring yet another phone to the world. Plus, it'd be really cool to
open and close a retro flip-phone (right???). Even the founders of the Light
Phone -- arguably, the most popular dumbphone -- thought it was too much for
them, and they have released a more featureful version <<light-phone-v1>>.

Don't get me wrong! I admire the Light Phone and all the work they do. This is
such a small industry that anything helps. Lots of people out there are really
happy with their minimal phones, and that's great. But there may be something
that could become more mainstream; the lower the barrier of entry, the better.
To be clear, this approach will also miss a lot of use-cases; as always, I'm
just scratching my own itches.

So what if we tried to find a middle point? There are two possible approaches:

* A dumbphone trying to be a smartphone
* Or a smartphone trying to be a dumbphone

I'm a bigger fan of the latter, because most dumbphones don't run Android. Given
how huge the mobile ecosystem is, it ends up being very restrictive to support
everyone's use-cases one by one. Your dumbphone's OS could add custom support
for Uber, but there may be someone who won't buy the phone unless it has
Spotify. And a password manager. And their banking app. And after implementing
all of these, someone will need a damned parking app for their apartment complex
<<parking>>.

The question arises: how in the world would you even manufacuture a phone? It
sounds like the most daunting task, especially given that I don't know anything
about hardware. Well, that's what I'll be researching in this series! It will
cover topics like studies about addiction, existing software and hardware for
digital control, phone manufacturing, EInk, or funding. I'm no expert, so let's
see how far the internet can take us.

== Looking at the state of things

I've been https://xkcd.com/356/[+++<s>nerdsniped</s>+++] drawn to this space for
some time, learning more about it from different perspectives:

=== Technology

Firstly, let's take a step back from "phones that shouldn't be used". Can we
generalize it to "tech that shouldn't be used"? Or rather, "tech that doesn't
unnecessarily grab your attention"? Well, then you'd be onto something! That's
precisely the definition of "https://en.wikipedia.org/wiki/Calm_technology[Calm
Technology]".

This is very centered around _design_, but still very much in our area.

=== Society

Is the population aware of
https://en.wikipedia.org/wiki/Problematic_smartphone_use[problematic smartphone
use]? Is it even a problem to them? There are countless studies on how phone
usage leads to isolation or TODO, but is anyone actually listening?

There are increasingly more stories about Hikikomori. But I don't want to focus
only on the extreme cases; in my experience, a large chunk of the population
thinks they use their phone too much. Other people are affected by the screens
themselves
<<light-sensitivity-1>><<light-sensitivity-2>><<light-sensitivity-3>>.

There's also the topic of phones for kids, but that's another huge rabbithole.
Or phones for elder.

=== Companies

In order to start a company that cares about people's mental health, it's
sensible to say that its workers shouldn't be crunching 60 hours per week. I
learned a lot about this by reading https://basecamp.com/books/calm["It doesn't
have to be crazy at work"], written by the founders of Basecamp. Part of its
contents are also available online
<<basecamp>><<basecamp-handbook>><<signalvnoise>>. You don't have to agree with
everything to admit it makes you re-think many things about how companies are
built.

This includes leadership, benefits, planning, hiring, funding... and how to make
them more reasonable. One takeaway is that if you start a business by trying to
change the world, the stakes will be too high from the start. This thought of
getting rich will be your justification for all-nighters and bad practices.
Other examples include few meetings, no long-term planning, the same salary for
everyone in the same level, a fixed portion of profits going to employees, or
perks like 32-hour working weeks in the summer.

Other so-called Calm Companies with this mentality include Transistor.fm
<<calm-transistor>><<build-your-saas>><<transistor-handbook>><<transistor-justin>>,
Wildbit (now ActiveCampaign) <<wildbit>>, or Convertkit <<convertkit>>, but
Basecamp is the loudest about it.

A cornerstone of this approach is ensuring the company stays true to its values.
In this case, that the less screen time, the better (within profitable means).
Not that the more revenue, the better. However, this is up to whoever has
control over the company, which is often whoever puts the money in. What Calm
Companies often do is bootstrapping and remaining private. Unfortunately, that
only works for purely-software companies; dealing with hardware means you will
need money. _A lot_ of money. The https://intl.nothing.tech/[Nothing company]
spends $30 to $50 million for each new product they develop <<nothing-money>>.
Or at "smaller" scale, the Light Phone 2 raised a total of $11.9 million in 2019
<<light-phone-money>>.

Nowadays, startups achieve funding _precisely_ by asserting they will change the
world. Their solution will blow the competition out of the water. Prepare to
invest RIGHT NOW or miss the train. It's just
https://en.wikipedia.org/wiki/Fear_of_missing_out[FOMO] for investors. How could
this work in the context of a Calm Company?

A popular choice for niche hardware is Crowdfunding. Bigme, reMarkable, Light
Phone, Minimal Phone, Librem. They all started like this. Though for what I've
learned, the money from the crowdfunding is actually only for the hardware
costs, not so much the upfront design and testing. The successful path seems to
be VC funding to set up the team and build a prototype, and then crowdfunding to
actually manufacture it. Going back to the Light Phone 2, they raised $3.5M on
IndieGoGo <<light-phone-igg>>, but also $8.4M in seed funding
<<light-phone-money>>. reMarkable also was able to secure $11M from presales,
but required an essential $10M in seed funding <<remarkable-money>>.

It's hard to avoid VC funding if you aren't already a billionaire. That would be
the case of https://mudita.com/[Mudita], founded by the already successful
Michał Kiciński, known for creating https://en.wikipedia.org/wiki/CD_Projekt[CD
Projekt]. I don't believe it's an impossible task; there are funds that leave
plenty of freedom to founders. There are also specialized firms for "Calm
Companies", although not many: CalmFund recently
https://calmfund.com/writing/pause[paused operations], and
https://www.indie.vc/[indie.vc] recently resumed theirs.

There are also strategies in how you set up the company to ensure long-term
TODO. OpenAI famously failed to do so, allegedly because raising money was too
hard as just a nonprofit <<openai>>. There are also certifications like
https://en.wikipedia.org/wiki/B_Corporation_(certification)[B Corporation] or
https://en.wikipedia.org/wiki/Social_enterprise[Social Enterprise], but I'm not
sure how effective they are.

You can see how much there is to further research in this topic. This is all
something I want to learn more about in future posts.

=== Software

By default, phones actually come with solid features to block apps and minimize
screen time in general. But they don't seem to be good enough to gain adoption.

Firstly, they aren't well marketed; most people aren't aware of their existence.
Android calls the features "https://www.android.com/digital-wellbeing/[Digital
Wellbeing]", but I personally receive more system notifications about new AI
features in my camera than things like this.

Secondly, they aren't first-party citizens; the tools are there, but they don't
quite integrate seamlessly. The most powerful feature on Android is "modes",
which allows you to switch between settings for different situations. For
example: when your GPS is in the library, disable Instagram and set the phone to
grayscale. Being so powerful, it's also complicated to configure (and to keep
your setup up to date). If the company was optimizing for less screen time
instead of ad revenue, we'd surely have more ideas to improve its adoption.

There are heaps of alternatives on the app marketplaces, although their source
code may not be available, and most have in-app payments or ads. Here are some
cool things I've seen while trying out Android apps <<apps>>:

- fancy tutorials,
- syncing across devices,
- blocking websites (or even features inside an app, like YouTube Shorts),
- blocking pre-bundled categories of apps and websites (such as shopping),
- breathing exercises before opening apps (or having to read a book),
- motivational quotes,
- forums,
- a floating timer indicating total usage on that day,
- notification filtering and bundling,
- gamification (competing against yourself or friends),
- comprehensive statistics,
- or having someone else to control your usage.

Not everything is limited to blocking apps; there are also minimal app launchers
<<launchers>> or simpler productivity timers <<timers>>. {{< app
name="minimalist phone" android="com.qqlabs.minimalistlauncher" >}} does well in
the "seamless experience" department, taking over your launcher and providing
ways to control how you open apps. I don't want to do an exhaustive analysis,
but just looking for "digital control" or "block apps" will already return many
results. It's worth downloading a few until you find your favorite anyway.

Manufacturers have it much easier, though, given that they have full system
access. For instance, the open-source app {{< app name="TimeLimit"
android="io.timelimit.android.google.store" >}} is an even more configurable
alternative to "Digital Wellness". But being external, it needs to start with a
long (and worrying) step to grant permissions. This alone is one step too many
to make it widespread -- I'd argue that even having to install it is too much.

To improve the user experience, some apps make emphasis on explaining how to use
their features. Others avoid it by trying to be smarter; they have your current
phone's usage data, so they already know which apps you use too much. One last
approach is to be opinionated and only support a subset of features that may
integrate better or have more impact. The Light Phone does this by only
providing their limited list of apps and features; if you're missing one, maybe
you'll get it, but maybe not.

Something else raising the barrier of entry is monetization. Although necessary,
some subscription models can be too much. A particularly creative app I liked
was {{< app name="Digital Detox" android="com.urbandroid.ddc" >}}, which makes
you pay $2 upon failing to meet your goals.

It's just great to have so many options, and not being locked in to any of them.
Different solutions for different people.

// The issue is that phones are essential for emergencies. Urgencies aren't just
// making a call, but also sending an important Slack message, making a
// transaction, or taking a photo of something you need to remember. Otherwise,
// it'd be super easy to just set a hard limit on how many hours you can spend, and
// ensure people don't cheat.

=== Accessories

Some products allow you to disable apps based on physical access to the device.
Requiring NFC to unlock apps can help break the habit of opening Instagram
automatically, turning it into a conscious decision. You can also block the apps
and leave the device at home to fully disconnect.

A couple of options are https://getbrick.app/[Brick] and
https://www.unpluq.com/[UnPluq]. They only solve part of the issue, though, and
UnPluq follows a subscription-based model that costs 70€ per year. Still, they
seem to work well for some folks, which is awesome.

=== Phones

What would a phone minimizing screen time look like?

A common pattern is the usage of e-paper displays. E-Paper is commonly seen on
e-readers, as an alternative that TODO. You can judge yourself:

++++
<iframe width="1600" height="400" src="https://www.youtube.com/embed/IFgxUr26A8g" title="E ink phone | YouTube | Linus Tech Tips | Hisense A9" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
++++

Hey, it's not a great experience for videos, but it doesn't take 5 seconds per
refresh like your crappy 10-year-old Kindle. For a display moving physical
particles <<epaper-physical>>, it's impressive. Here's another monitor that
recently came out focusing on latency:

++++
<iframe width="1600" height="400" src="https://www.youtube.com/embed/pXn-bAwzNv4?start=183" title="Modos Paper Monitor Status Update" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
++++

A common feature in e-paper is that it's grayscale. Not having colors is linked
with reducing addiction [TODO link][TODO Carl pei talking about this], but it
can be annoying sometimes. I've set my day-to-day phone to grayscale, and I know
how confusing Google Maps can be without colors. If you come across a chart
relying on colors, you'll need to watch it somewhere else. And I haven't even
tried gaming. One could argue that this is a feature, making you use different
devices for different purposes, and thus, separating a bit better your digital
life use-cases.

For this, there's now color e-paper, with Kindle releasing its first version in
2014 [TODO: link]. It comes with drawbacks, such as having worse refresh rates
or a lower contrast ratio.

Another characteristic about e-paper is its refresh rate. Even if it has gotten
more decent in recent generations, it makes it harder to watch videos on YouTube
or Netflix, although one could argue that's a feature, not a bug. I've recently
seen a wave of e-paper products focusing on fast refresh times [TODO
sunlight][TODO oss project], so I'm positive that will improve.

The most popular brands are HiSense and Boox, but they aren't well-supported in
the west. Apps might not work sometimes, and connectivity only works with some
providers, if at all <<hisense-review>><<boox-connectivity>>. Boox is known for
violating the GPL, too <<boox-gpl>>. There are startups releasing similar
devices, but they have a long road ahead. Mudita will announce a new phone soon
<<mudita-release>>, and Daylight might work on a phone after their $729 tablet
with different screen tech ships <<daylight-release>><<daylight-podcast>>.

A simpler approach to consider is what https://ghostmode.us/[Ghost Mode] does.
They lock down a Pixel 6a into a dumbphone, keep its nice camera, and resell it.
No need to deal with manufacturers, and your software has system access. But
costing $600, they have a pricy product, and being dependent on Google is often
not a good idea.

Anyhow, I plan on diving
deeper into this in a later article; there's also a lot that can be done on the
software to overcome the limitations of e-paper.

== Wrapping up

I hope this can eventually be "a thing". Just like there are movements for
"sustainability" or "diversity", there should also be for better digital
control. To me, it has a strong relationship with mental health, and there's a
lot to improve in that regard.

There is a lot more to research in each of these sections. I will try to split
it up into multiple articles within
https://nullderef.com/series/dont-use-this-phone/[the series]. You can
https://nullderef.com/subscribe[subscribe] for free to keep up to date. Actually
building something in this area would be exciting. Manufacturing a phone sounds
like a crazy idea, but who knows where the future will take you :)

[bibliography]
== References

- [[[basecamp,           1]]]
  https://37signals.com/[37signals (the company that owns Basecamp)]
- [[[basecamp-handbook,  2]]]
  https://basecamp.com/handbook[The 37signals Employee Handbook]
- [[[signalvnoise,        3]]]
  https://signalvnoise.com/[Signal v. Noise (37signals' former blog)]
- [[[light-phone-v1,      4]]]
  https://www.theverge.com/2019/9/4/20847717/light-phone-2-minimalist-features-design-keyboard-crowdfunding[The
  high hopes of the low-tech phone -- The Verge]
- [[[parking,             5]]]
  https://www.reddit.com/r/dumbphones/comments/sjtkm2/i_have_to_use_an_app_to_open_my_apartment_complex/[I
  have to use an app to open my apartment complex parking gate, the app is
  called Gatewise. My lease does not mention anything about needing a smartphone
  or the use of any apps for garage access. Street parking is not an option. I
  just want technological equity -- r/dumbphones]
- [[[calm-transistor,     6]]]
  https://www.reddit.com/r/SaaS/comments/nrjsao/im_40_years_old_and_i_finally_bootstrapped_a_saas/[I'm
  40 years old and I finally bootstrapped a SaaS, Transistor.fm, to millions in
  revenue (with a co-founder!) -- r/SaaS]
- [[[build-your-saas,     7]]]
  https://saas.transistor.fm/episodes[Build Your SaaS -- transistor.fm]
- [[[transistor-handbook, 8]]]
  https://github.com/TransistorFM/handbook/blob/master/values.md[What are our
  values? -- GitHub TransistorFM/handbook]
- [[[transistor-justin,   9]]]
  https://justinjackson.ca/[Justin Jackson (co-founder of Transistor.fm)]
- [[[wildbit,            10]]]
  https://wildbit.com/[Wildbit]
- [[[convertkit,         11]]]
  https://convertkit.com/handbook[The ConvertKit Team Handbook]
- [[[apps,               12]]]
  Digital control:
    {{< app name="AppBlock" android="cz.mobilesoft.appblock" >}},
    {{< app name="Freedom" android="to.freedom.android2" ios="freedom-screen-time-control/id1269788228" >}},
    {{< app name="YourHour" android="com.mindefy.phoneaddiction.mobilepe" >}},
    {{< app name="Digital Detox" android="com.urbandroid.ddc" >}},
    {{< app name="StayFree" android="com.burockgames.timeclocker" >}},
    {{< app name="Stay Focused" android="com.stayfocused" >}},
    {{< app name="StayOff" android="com.app.floatingapptimer.com" >}},
    {{< app name="ActionDash" android="com.actiondash.playstore" >}},
    {{< app name="ClearSpace" ios="clearspace-reduce-screen-time/id1572515807" >}},
    {{< app name="Refocus" ios="refocus-app-website-blocker/id1645639057" >}},
    {{< app name="Opal" ios="opal-screen-time-for-focus/id1497465230" >}}
    {{< app name="Jomo" ios="jomo-screen-time-blocker/id1609960918" >}}
- [[[launchers,          13]]]
  Launchers:
    {{< app name="Olauncher" android="app.olauncher" >}},
    {{< app name="minimalist phone" android="com.qqlabs.minimalistlauncher" >}},
    {{< app name="Indistract" android="com.indistractablelauncher.android" >}},
    {{< app name="Blank Spaces" ios="blank-spaces-app/id1570856853" >}}
- [[[timers,             14]]]
  Productivity timers:
    {{< app name="Forest" android="cc.forestapp" >}},
    {{< app name="Flora" ios="flora-green-focus/id1225155794" >}},
    {{< app name="Plantie" ios="plantie-stay-focused/id1135988868" >}}
- [[[nothing-money,      15]]]
	https://youtu.be/dDI9h4ool-E?t=1549[Nothing CEO Carl Pei on the Phone 2 and
	the future of gadgets | The Vergecast -- YouTube] @ 25:49
- [[[light-phone-money,  16]]]
	https://www.businessinsider.com/light-phone-2-dumb-phone-price-release-date-specs-2019-9[This
	credit-card-size phone can do only 3 things and doesn't have any apps — and it
	may be the key to freeing us from our smartphones -- Business Insider]
- [[[light-phone-igg,    17]]]
	https://www.indiegogo.com/projects/light-phone-2#/[Light Phone 2 -- IndieGoGo]
- [[[remarkable-money,   18]]]
	https://venturebeat.com/media/remarkable-raises-15-million-to-bring-its-e-paper-tablets-to-more-scribblers/[Remarkable
	raises $15 million to bring its e-paper tablets to more scribblers --
	VentureBeat]
- [[[openai,             19]]]
  https://openai.com/our-structure/[Our structure -- OpenAI]
- [[[light-sensitivity-1,20]]]
  https://ledstrain.org/[LEDStrain Forum]
- [[[light-sensitivity-2,21]]]
	https://www.reddit.com/r/ChronicPain/comments/b936z9/has_anyone_here_been_diagnosed_with_central/[Has
	anyone here been diagnosed with central sensitization and/or relate somehow
	to my story? (36M, pain started at 33) -- r/ChronicPain]
- [[[light-sensitivity-3,22]]]
	https://www.reddit.com/r/eink/comments/g3kiki/an_open_letter_to_google_google_if_you_care_about/[An
	open letter to Google : Google, if you care about accessibility, please stop
	undermining the development of e-ink smartphones. Those are life savers for a
	growing number of people like me who can no longer use regular screens. --
	r/eink]
- [[[boox-gpl,           23]]]
	https://en.wikipedia.org/wiki/Onyx_Boox#GPL_Compliance[GPL Compliance, Onyx
	Boox -- Wikipedia]
- [[[mudita-release,     24]]]
	https://mudita.com/community/blog/introducing-mudita-kompakt/[First glimpse of
	Mudita Kompakt -- Mudita]
- [[[daylight-release,   25]]]
	https://www.theverge.com/2024/5/23/24163225/daylight-dc1-tablet-livepaper[The
	Daylight DC1 is a $729 attempt to build a calmer computer -- The Verge]
- [[[hisense-review,     26]]]
	https://www.reddit.com/r/eink/comments/10hl3bv/hisense_a9_1_week_review/[Hisense
	A9 - 1 Week Review -- r/eink]
- [[[boox-connectivity,  27]]]
	https://help.boox.com/hc/en-us/community/posts/15815361554068-Why-oh-why-no-SIM-card-mobile-data-support[Why
	oh why no SIM-card / mobile data support? -- Boox Forums]
- [[[daylight-podcast,   28]]] https://youtu.be/2Y1nogFltPY?t=2240[Episode #234:
	Anjan Katta (Founder of Daylight Computer Co) -- YouTube] @ 37:20
- [[[epaper-physical,    29]]]
	https://en.wikipedia.org/wiki/Electronic_paper#Electrophoretic[Electrophoretic,
	Electronic paper -- Wikipedia]
