---
title: "A phone designed not to be used: what would it take to build one?"
description: "TODO"
author: "Mario Ortiz Manero"
images: ["TODO"]
tags: ["tech"]
series: ["dont-use-this-phone"]
date: 2024-06-01
GHissueID: TODO
draft: true
---

TODO: fill out description in series/dont-use-this-phone/_index.md

What if there was a company selling phones that, against all odds, optimized how
_little_ they were used? Given that every company is trying to get you hooked
into their app, there's so much that can be done here.

We have "https://en.wikipedia.org/wiki/Feature_phone[dumbphones]", for example.
These are phones whose functionality is intentionally locked down, with the
purest examples only supporting calls and SMS. On the other side of the
spectrum, we have smartphones. It wouldn't be far-fetched to say that most
people owning one use it more than they'd like.

I've seen people around me switching to a dumbphone. It's not a bad idea; it
helps them reduce anxiety in the short term. But in the longer term, it turns
out to be impossible. Firstly, because some apps like WhatsApp or Lyft can be
indispensable for many. And secondly, because using most apps within reasonable
means are an improvement in quality of life. A GPS can be of immense help
getting around, or even Netflix can be a great ally to fight boredom in a plane.

And as a big fan of second-hand stuff, I'd rather give an old Motorola a second
life than bring yet another phone to the world. Plus, it'd be really cool to
open and close a retro flip-phone (right???). Even the founders of the Light
Phone -- arguably, the most popular dumbphone -- thought it was too much for
them, and they have released a more featureful version <<light-phone-v1>>.

Don't get me wrong! I admire the Light Phone and all the work they do. This is
such a small industry that anything helps. Lots of people out there are really
happy with their minimal phones, and that's great. But there may be something
that could become more mainstream; the lower the barrier of entry, the better.
To be clear, this approach will also miss a lot of use-cases; as always, I'm
just scratching my own itches.

So what if we tried to find a middle point? There are two possible approaches:

* A dumbphone trying to be a smartphone
* Or a smartphone trying to be a dumbphone

I'm a bigger fan of the latter, because most dumbphones don't run Android. Given
how huge the mobile ecosystem is, it ends up being very restrictive to support
everyone's use-cases one by one. Your dumbphone's OS could add custom support
for Uber, but there may be someone who won't buy the phone unless it has
Spotify. And a password manager. And their banking app. And after implementing
all of these, someone will need a damned parking app for their apartment complex
<<parking>>.

The question arises: how in the world would you even manufacuture a phone? It
sounds like the most daunting task, especially given that I don't know anything
about hardware. Well, that's what I'll be researching in this series! It will
cover topics like studies about addiction, existing software and hardware for
digital control, phone manufacturing, EInk, or funding. I'm no expert, so let's
see how far the internet can take us.

== Looking at the state of things

I've been https://xkcd.com/356/[+++<s>nerdsniped</s>+++] drawn to this space for
some time, learning more about it from different perspectives:

=== Technology

Firstly, let's take a step back from "phones that shouldn't be used". Can we
generalize it to "tech that shouldn't be used"? Or rather, "tech that doesn't
unnecessarily grab your attention"? Well, then you'd be onto something! That's
precisely the definition of "https://en.wikipedia.org/wiki/Calm_technology[Calm
Technology]".

This is very centered around _design_, but still very much in our area.

=== Society

Is the population aware of this being a problem? Is it even a problem to them?
There are countless studies on how phone usage leads to isolation or TODO, but
is anyone actually listening?

=== Companies

In order to start a company that cares about people's mental health, it's
sensible to say that its workers shouldn't be crunching 60 hours per week.
Additionally, how can you keep the company from deviating from its original
objective?

Most of my learnings here come from reading "It doesn't have to be crazy at
work", written by the founders of Basecamp. Other so-called Calm Companies
include Balsamiq, Transistor.fm
<<calm-transistor>><<build-your-saas>><<transistor-handbook>><<transistor-justin>>,
Wildbit <<wildbit>>, or Convertkit <<convertkit>>, but Basecamp is the loudest
about it.

The book makes you re-think many things you take for granted about how companies
are built. Leadership, benefits, planning, hiring, funding... And in which ways
one can make it more sane overall. One of my takeaways was that if you start a
company by thinking you'll change the world, the stakes will be higher from the
start. Similarly, if you start it thinking you'll become rich, that's when the
problems start to happen.

However, a major question remains: funding. These companies are able to stick to
their morals by bootstrapping and remaining private, essentially. Unfortunately,
that only works for purely-software companies; dealing with hardware means you
will need money. _A lot_ of money. Light Phone 2 raised $3.3M; made up of an
upfront expense for designing and planning, and the actual building ($2M) [TODO
REF].

But startups achieve funding _precisely_ by asserting they will change the
world. Their solution will blow the competition out of the water. Prepare to
invest RIGHT NOW or miss the train. It's just FOMO for investors. How could this
work in the context of a Calm Company?

A popular choice for custom hardware is Crowdfunding. Bigme, Remarkable, Light
Phone, Minimal Phone, Librem. They all started like this. Though for what I've
learned, the money from the crowdfunding is actually only for the building
costs, not so much the upfront design. The successful path seems to be VC
funding to set up the team and build a prototype, and then crowdfunding to
actually manufacture it. This is also when stuff starts to go wrong. There are
always endless delays when crowdfunding, and if you don't design it well enough,
your whole project will look like a scam. This has happened many times already.

So, yes. It's hard to avoid VC funding. There are specialized firms, but it's a
minority. CalmFund, which recently https://calmfund.com/writing/pause[paused
operations], and https://www.indie.vc/[indie.vc], which recently resumed theirs.

I'm building on top of the naïve assumption that the less screen time, the
better off the company is.

So how do you prevent VC from leading too much? OpenAI already failed to do so,
allegedly because raising money was too hard [REFERENCE]. Nonprofits have it
harder [TODO]. There are certifications like
https://en.m.wikipedia.org/wiki/B_Corporation_(certification)[B Corporation] or
https://en.m.wikipedia.org/wiki/Social_enterprise[Social Enterprise], too
[EXAMPLES]. I plan on doing a deep dive of this section soon, anyway.

- https://www.onepercentfortheplanet.org/[One Percent for the Planet]
- https://stripe.com/en-ca/climate[Stripe Climate]

=== Software

By default, phones actually come with solid features to block apps and minimize
screen time in general. However, they don't seem to be good enough to gain
adoption.

Firstly, they aren't well marketed; most people aren't aware of their existence.
Android calls the features "https://www.android.com/digital-wellbeing/[Digital
Wellbeing]", but I personally receive more system notifications about new AI
features in my camera than things like this.

Secondly, they aren't first-party citizens; the tools are there, but they don't
quite integrate seamlessly. The most powerful feature on Android is "modes",
which allows you to switch between settings for different situations. For
example: when your GPS is in the library, disable Instagram and set the phone to
grayscale. Being so powerful, it's also complicated to configure (and to keep
your setup up to date). If the company was optimizing for less screen time
instead of ad revenue, we'd surely have more ideas to improve its adoption.

There are heaps of alternatives on the app marketplaces, although their source
code may not be available, and most have in-app payments or ads. Here are some
cool things I've seen while trying out Android apps <<apps>>:

- fancy tutorials,
- syncing across devices,
- blocking websites (or even features inside an app, like YouTube Shorts),
- blocking pre-bundled categories of apps and websites (such as shopping),
- breathing exercises before opening apps (or having to read a book),
- motivational quotes,
- forums,
- a floating timer indicating total usage on that day,
- notification filtering and bundling,
- gamification (competing against yourself or friends),
- comprehensive statistics,
- or having someone else to control your usage.

Not everything is limited to blocking apps; there are also minimal app launchers
<<launchers>> or simpler productivity timers <<timers>>. {{< app
name="minimalist phone" android="com.qqlabs.minimalistlauncher" >}} does well in
the "seamless experience" department, taking over your launcher and providing
ways to control how you open apps. I don't want to do an exhaustive analysis,
but just looking for "digital control" or "block apps" will already return many
results. It's worth downloading a few until you find your favorite anyway.

Manufacturers have it much easier, though, given that they have full system
access. For instance, the open-source app {{< app name="TimeLimit"
android="io.timelimit.android.google.store" >}} is an even more configurable
alternative to "Digital Wellness". But being external, it needs to start with a
long (and worrying) step to grant permissions. This alone is one step too many
to make it widespread -- I'd argue that even having to install it is too much.

To improve the user experience, some apps make emphasis on explaining how to use
their features. Others avoid it by trying to be smarter; they have your current
phone's usage data, so they already know which apps you use too much. One last
approach is to be opinionated and only support a subset of features that may
integrate better or have more impact. The Light Phone does this by only
providing their limited list of apps and features; if you're missing one, maybe
you'll get it, but maybe not.

Something else raising the barrier of entry is monetization. Although necessary,
some subscription models can be too much. A particularly creative app I liked
was {{< app name="Digital Detox" android="com.urbandroid.ddc" >}}, which makes
you pay $2 upon failing to meet your goals.

It's just great to have so many options, and not being locked in to any of them.
Different solutions for different people.

// The issue is that phones are essential for emergencies. Urgencies aren't just
// making a call, but also sending an important Slack message, making a
// transaction, or taking a photo of something you need to remember. Otherwise,
// it'd be super easy to just set a hard limit on how many hours you can spend, and
// ensure people don't cheat.

=== Accessories

Some products allow you to disable apps based on physical access to the device.
Requiring NFC to unlock apps can help break the habit of opening Instagram
automatically, turning it into a conscious decision. You can also block the apps
and leave the device at home to fully disconnect.

A couple of options are https://getbrick.app/[Brick] and
https://www.unpluq.com/[UnPluq]. They only solve part of the issue, though, and
UnPluq follows a subscription-based model that costs 70€ per year. Still, they
seem to work well for some folks, which is awesome.

=== Phones

A common pattern is the usage of EInk displays. EInk is commonly seen on
e-readers, as an alternative that TODO. And it turns out that its
performance can be much better than your crappy Kindle, which takes 5 seconds to
skip to the next page. There's even now color EInk, with Kindle releasing its
first version in 2014 [TODO: link].

TODO: VIDEO

Some of the most popular brands are HiSense and Boox. However, they aren't that
well marketed nor supported outside of Asia. There are also some new startups
catching up releasing new devices, such as Mudita or Daylight, but they aren't
quite there yet. Anyhow, I plan on diving deeper into this in a later article.

A simpler approach is what GHOST does. Based on the Pixel, they make some
modifications and resell it. No need to deal with manufacturers.

== Wrapping up

I hope this can eventually be "a thing". Just like there are movements for
"sustainability" or "diversity", there should also be for better digital
control. To me, it has a strong relationship with mental health, and there's a
lot to improve in that regard.

Building something in this area would be exciting. Manufacturing a phone sounds
like a crazy idea, but who knows where the future will take you :)

[bibliography]
== References

- [[[light-phone-v1, 1]]]
  https://www.theverge.com/2019/9/4/20847717/light-phone-2-minimalist-features-design-keyboard-crowdfunding[The
  high hopes of the low-tech phone -- The Verge]
- [[[parking,        2]]]
  https://www.reddit.com/r/dumbphones/comments/sjtkm2/i_have_to_use_an_app_to_open_my_apartment_complex/[I
  have to use an app to open my apartment complex parking gate, the app is
  called Gatewise. My lease does not mention anything about needing a smartphone
  or the use of any apps for garage access. Street parking is not an option. I
  just want technological equity -- r/dumbphones]
- [[[calm-transistor,3]]]
  https://www.reddit.com/r/SaaS/comments/nrjsao/im_40_years_old_and_i_finally_bootstrapped_a_saas/[I'm
  40 years old and I finally bootstrapped a SaaS, Transistor.fm, to millions in
  revenue (with a co-founder!) -- r/SaaS]
- [[[build-your-saas,4]]]
  https://saas.transistor.fm/episodes[Build Your SaaS -- transistor.fm]
- [[[transistor-handbook, 5]]]
  https://github.com/TransistorFM/handbook/blob/master/values.md[What are our
  values? -- GitHub TransistorFM/handbook]
- [[[transistor-justin,  6]]] https://justinjackson.ca/[Justin Jackson
  (co-founder of Transistor.fm)]
- [[[wildbit,        6]]] https://wildbit.com/[Wildbit]
- [[[convertkit,     7]]] https://convertkit.com/handbook[The ConvertKit Team
  Handbook]
- [[[apps,           3]]] Digital control:
    {{< app name="AppBlock" android="cz.mobilesoft.appblock" >}},
    {{< app name="Freedom" android="to.freedom.android2" ios="freedom-screen-time-control/id1269788228" >}},
    {{< app name="YourHour" android="com.mindefy.phoneaddiction.mobilepe" >}},
    {{< app name="Digital Detox" android="com.urbandroid.ddc" >}},
    {{< app name="StayFree" android="com.burockgames.timeclocker" >}},
    {{< app name="Stay Focused" android="com.stayfocused" >}},
    {{< app name="StayOff" android="com.app.floatingapptimer.com" >}},
    {{< app name="ActionDash" android="com.actiondash.playstore" >}},
    {{< app name="ClearSpace" ios="clearspace-reduce-screen-time/id1572515807" >}},
    {{< app name="Refocus" ios="refocus-app-website-blocker/id1645639057" >}},
    {{< app name="Opal" ios="opal-screen-time-for-focus/id1497465230" >}}
    {{< app name="Jomo" ios="jomo-screen-time-blocker/id1609960918" >}}
- [[[launchers,      4]]] Launchers:
    {{< app name="Olauncher" android="app.olauncher" >}},
    {{< app name="minimalist phone" android="com.qqlabs.minimalistlauncher" >}},
    {{< app name="Indistract" android="com.indistractablelauncher.android" >}},
    {{< app name="Blank Spaces" ios="blank-spaces-app/id1570856853" >}}
- [[[timers,         5]]] Productivity timers:
    {{< app name="Forest" android="cc.forestapp" >}},
    {{< app name="Flora" ios="flora-green-focus/id1225155794" >}},
    {{< app name="Plantie" ios="plantie-stay-focused/id1135988868" >}}
