---
title: "Beyond Dumbphones: Building a Minimalist Yet Functional Phone"
description: "Ever feel like your phone controls you? Can we design a smartphone
that minimized how much you used it?"
author: "Mario Ortiz Manero"
images: ["/blog/phone-intro/cover.jpg"]
tags: ["tech", "phone dependency", "addiction", "eink", "calm companies",
"dumbphones", "phone manufacturing"]
series: ["dont-use-this-phone"]
date: 2024-06-01
GHissueID: 13
---

What if there was a company selling phones that, against all odds, optimized how
_little_ they were used? There's a lot of potential here, given that every
company is trying to get you hooked on their app.

https://en.wikipedia.org/wiki/Feature_phone["`Dumbphones`"] have emerged for
this very reason. These are phones whose functionality is intentionally locked
down, with the purest examples only supporting calls and SMS. On the other side
of the spectrum, we have smartphones. It wouldn't be far-fetched to say that
most people owning one use it more than they'd like.

I've seen people around me switching to a dumbphone. A _digital detox_ is not a
bad idea; it helps reduce anxiety in the short term. But in the longer term,
it's pretty much impossible. A few apps like WhatsApp or Google Maps can be
indispensable, and the rest actually improve our lifes when used reasonably.
TikTok can be incredibly addicting, but it's arguably a great way for people to
learn, relax, or connect with others.

Even the founders of the https://en.wikipedia.org/wiki/Light_Phone[Light Phone]
-- the most popular dumbphone brand -- thought it was too restrictive for them,
and they have released a more featureful version&nbsp;<<light-phone-v1>>. Don't
get me wrong! I admire the company and all the work they do; this is such a
small industry that anything helps. But I wonder if there's something that could
become more mainstream.

Besides, as a big fan of second-hand stuff, I'd rather give an old Motorola a
second life than bring yet another phone to the world. It'd also be really cool
to open and close a retro flip-phone (right???).

So what if we tried to find a middle point? There are two possible approaches:

. A dumbphone trying to be a smartphone
. Or a smartphone trying to be a dumbphone

I'm a bigger fan of the latter, because most dumbphones don't give you direct
access to an app store. Given how huge the mobile ecosystem is, supporting
everyone's use-cases one by one ends up being very restrictive. Your dumbphone's
operating system could add custom support for Uber, but there may be someone who
won't buy the phone unless it has Spotify. And a password manager. And their
banking app. And after implementing all of these, someone will need a damned
parking app for their apartment complex (yes, really&nbsp;<<parking>>).

The question arises: how in the world would you even manufacture a phone? It
sounds like the most daunting task, so that's what I'll be researching in this
series! We'll get started with broader topics like addiction, building
companies, or existing solutions, and eventually get into more details. I'm no
expert, so let's see how far the internet can take us.

== Looking at the state of things

I've been https://xkcd.com/356/[+++<s>nerdsniped</s>+++] drawn to this space for
some time, learning more about it from different perspectives:

=== Technology

Firstly, let's take a step back from "`phones that shouldn't be used`". Can we
generalize it to "`tech that shouldn't be used`"? Or rather, "`tech that doesn't
unnecessarily grab your attention`"? Now we're onto something! That's what
https://en.wikipedia.org/wiki/Calm_technology["`Calm Technology`"] is all about,
a concept coined by Mark Weiser and John Seely Brown at
https://en.wikipedia.org/wiki/PARC_(company)[XEROX Parc] in the '90s.

Calm Technology describes design principles that let a piece of technology
_inform_ the user without _demanding_ their attention. Anything from hammers to
Roombas can be considered "`calm`". Researcher Amber Case
https://calmtech.com/[picked up on this] and recently announced
https://www.calmtech.institute/[an institute] to certify products that meet
these standards. Also inspired by Mark and John's original work, Jon Yablonski
shares his take and more resources in his website
https://humanebydesign.com/[Humane By Design].

The https://www.humanetech.com/[Center for Humane Technology] is a more
established organization on this topic. This non-profit aims to educate people
and companies, raise awareness, and aid in policymaking. It gained popularity in
Neflix's hit documentary https://www.thesocialdilemma.com/[_The Social
Dilemma_], which focuses on social media. One of its founders, Tristan Harris,
created http://www.minimizedistraction.com/[an internal presentation at Google]
in 2013 that has aged like fine wine.

On the flip side, Cal Newport writes about what _humans_ can do to stop their
attention from being hijacked. He calls it
https://www.goodreads.com/book/show/40672036-digital-minimalism["`Digital
Minimalism`"] and also covers managing your attention span in
https://www.goodreads.com/book/show/25744928-deep-work["`Deep Work`"], or living
a more minimalist life in general. This is also discussed on
https://nosurf.net/[NoSurf], the biggest community on the topic I could find,
with even more information&nbsp;<<nosurf-resources>>.

=== Negative effects

Is the population aware of
https://en.wikipedia.org/wiki/Problematic_smartphone_use[problematic smartphone
use]? Is it even a problem to them? Certainly, there are studies on how phone
usage leads to poorer psychological health. But it doesn't help that there's no
medical consensus nor recognition; https://youtu.be/8B271L3NtAw?t=10[there's
correlation, but not clear causation]&nbsp;<<phone-depression>>

Phones have undoubtedly impacted our society. Some changes are good, others, not
so much. We fiddle with our phones to avoid eye contact, social media worsens
our self-esteem, and we have attention issues. It's just hard to be bored
anymore, which is actually good for you&nbsp;<<bored>><<bored-2>>. Phones also
disrupt our sleep cycles&nbsp;<<phones-sleep-filter>>, and cars frequently crash
because of them&nbsp;<<phones-crash>>. Nothing you don't already know.

There are increasingly more stories about
https://en.wikipedia.org/wiki/Hikikomori[Hikikomori], described as "`total
withdrawal from society and seeking extreme degrees of social isolation and
confinement`". Of course, it's not limited to Japan. Wikipedia sheds light on
the role of technology in this condition:

[quote, Wikipedia]
____
Although the connection between modern communication technologies (such as the
Internet, social media and video games) and the phenomenon is not conclusively
established, those technologies are considered at least an exacerbating factor
that can deepen and nurture withdrawal.
____

It even specifically mentions our topic:

[quote, Wikipedia]
____
The emergence of mobile phones and then smartphones may also have deepened the
issue, given that people can continue their addiction to gaming and online
surfing anywhere, even in bed.
____

Some people suffering from migraines or light sensitivity are affected by the
screen itself&nbsp;<<light-sensitivity-1>><<light-sensitivity-2>>. There's also
the topic of phones for children or the elderly, but that's a huge rabbit hole.
Looking at the broader population, nearly 6 in 10 U.S. smartphone users admit
that they use their phone too much&nbsp;<<gallup-survey>>. So the good news is
that people are at least aware of the issue. That surely means there's a need
for solutions, regardless of science?

=== Companies

In order to start a company that cares about people's mental health, it's
sensible to say that its workers shouldn't be crunching 60 hours per week. I
learned a lot about this by reading https://basecamp.com/books/calm["`It doesn't
have to be crazy at work`"], written by the founders of Basecamp. Part of its
contents are also available
online&nbsp;<<basecamp>><<basecamp-handbook>><<signalvnoise>>. You don't have to
agree with everything to admit it makes you rethink how companies are built.

This includes leadership, benefits, planning, hiring, funding... and how to make
them more reasonable. One key idea is that starting a business with the goal of
changing the world sets the stakes too high from the beginning. The desire to
get rich becomes the justification for all-nighters and bad practices, which
spreads from founders to employees. Other so-called "`Calm Companies`" that
share this mindset include
Transistor.fm&nbsp;<<calm-transistor>><<build-your-saas>><<transistor-handbook>><<transistor-justin>>,
Wildbit&nbsp;<<wildbit>>, or Convertkit&nbsp;<<convertkit>>, but Basecamp is the
loudest about it.

An important caveat is that we must ensure the company stays true to its values.
In this case, that the less screen time, the better (within profitable means).
Not that the more revenue, the better. However, this depends on who controls the
company, which is often the person who provides the funding.

We can learn this lesson from
https://en.wikipedia.org/wiki/CouchSurfing[CouchSurfing], a website that helps
you find a couch at someone's home for a short stay. The company's goal wasn't
just to "`connect hosts to guests`", but to "`create lasting positive
experiences and relationships between strangers`". And it wasn't gibberish:
their internal metric for success was "`positive time had thanks to
CouchSurfing`" subtracted by "`time spent on the
website`"&nbsp;<<tristan-distraction>>. But after a hectic story, they changed
to a for-profit and started heading in the opposite direction, fueled by the
need for monetization&nbsp;<<couch-end>>.

What most Calm Companies do is _bootstrap_, meaning the founders use their own
money. They promise never to go public, and Basecamp goes a step further by
assuring they will never sell the company&nbsp;<<basecamp-basic>>.
Unfortunately, that only works for purely software companies; manufacturing
hardware means you will need money. The https://intl.nothing.tech/[Nothing
company] spends $30 to $50 million for each new product they
develop&nbsp;<<nothing-money>>. On a "`smaller`" scale, the Light Phone 2 raised
a total of $11.9 million in 2019&nbsp;<<light-phone-money>>. You'd probably do
fine with much less, but it shows how hard it'd be to save up that kind of money
yourself.

A popular choice for niche hardware is
https://en.wikipedia.org/wiki/Crowdfunding[crowdfunding], where the money comes
from a bunch of interested people on the internet. Bigme, reMarkable, Light
Phone, Minimal Phone, Librem. They all started like this. But from what I've
learned, the crowdfunded money usually only covers the hardware costs, not so
much the upfront design and testing. The successful path seems to be
https://en.wikipedia.org/wiki/Venture_capital[Venture Capital (VC) funding] to
set up the team and build a prototype, and then crowdfunding to actually
manufacture it.

Going back to the Light Phone 2, they raised $3.5M from consumers on
IndieGoGo&nbsp;<<light-phone-igg>> but also $8.4M in seed
funding&nbsp;<<light-phone-money>>. Similarly, reMarkable was able to secure
$11M from presales but required an essential $10M in seed
funding&nbsp;<<remarkable-money>>. It's hard to avoid VC funding if you aren't
already a billionaire, like in the case of https://mudita.com/[Mudita]. This
company was founded by Michał Kiciński, who had already succeeded with
https://en.wikipedia.org/wiki/CD_Projekt[CD Projekt]&nbsp;<<mudita-funding>>.

Nowadays, startups raise VC money _precisely_ by asserting they will change the
world. Their solution will blow the competition out of the water. Prepare to
invest RIGHT NOW or miss the train. It's just
https://en.wikipedia.org/wiki/Fear_of_missing_out[FOMO] for investors. How could
this work in the context of a Calm Company?

Although harder, I don't believe it's impossible. There are funds that leave
plenty of freedom to the founders. And a minority of them are specialized in
Calm Companies, such as CalmFund (which just
https://calmfund.com/writing/pause[paused operations]),
https://www.indie.vc/[indie.vc], or https://tinyseed.com/[tinyseed].

Once you get over the necessity of raising money, there are other ways to
preserve the company's ideals. OpenAI famously failed to do so as a pure
non-profit, allegedly because raising money was too hard as just a
nonprofit&nbsp;<<openai>>. So maybe we could take that as a learned lesson.
Other ideas are certifications like
https://en.wikipedia.org/wiki/B_Corporation_(certification)[B Corporation] or
https://en.wikipedia.org/wiki/Social_enterprise[Social Enterprise], but I'm not
sure how effective they are.

You can see how much more I can research about this topic in future posts. And
we haven't even gotten to the phones section yet!

=== Software

Smartphones actually come with solid features to block apps and minimize screen
time in general. However, they don't seem to be good enough to gain adoption.

Firstly, they aren't well marketed; most people aren't aware of their existence.
Android calls the features https://www.android.com/digital-wellbeing/["`Digital
Wellbeing`"] and iOS
https://support.apple.com/guide/iphone/get-started-with-screen-time-iphbfa595995/ios["`Screen
Time`"]. Personally, I receive more system notifications about new AI features
in my camera than things like this.

Secondly, they aren't first-party citizens; the tools are there, but they don't
quite integrate seamlessly. The most powerful feature on Android is "`modes`",
which allows you to switch settings for different situations. For example: when
your GPS shows you're in the library, it can disable Instagram and set the
screen to grayscale. Being so powerful, it's also complicated to configure (and
to keep your setup up to date). If the company prioritized reducing screen time
over ad revenue, we’d likely see more ideas to improve its adoption.

There are heaps of alternatives on the app marketplaces, although their source
code may not be available, and most have in-app payments or ads. Here are some
cool features I've seen while trying out Android apps&nbsp;<<apps>>:

- fancy tutorials,
- syncing across devices (including your laptop or tablet),
- blocking websites (or even features inside an app, like YouTube Shorts),
- blocking pre-bundled categories of apps and websites (such as "`shopping`"),
- breathing exercises before opening apps (or having to read a book),
- motivational quotes,
- forums,
- a floating timer indicating total usage on that day,
- notification filtering and bundling,
- https://en.wikipedia.org/wiki/Gamification[gamification] (competing against
  yourself or friends),
- comprehensive statistics,
- or having someone else to control your usage.

Not everything is limited to blocking apps; there are also minimal app
launchers&nbsp;<<launchers>> or simple productivity timers&nbsp;<<timers>>. {{<
app name="minimalist phone" android="com.qqlabs.minimalistlauncher" >}} does
well in the "`seamless experience`" department by filtering notifications and
taking over your launcher to control how you open apps. I don't want to do an
exhaustive analysis, but just searching "`screentime`" will already return many
results on the app store. It's worth downloading a few until you find your
favorite anyway.

However, manufacturers have it much easier, given that they have full system
access over your phone. For instance, the open-source app {{< app
name="TimeLimit" android="io.timelimit.android.google.store" >}} is an even more
configurable alternative to "`Digital Wellbeing`". But being external, it needs
to start with a long (and worrying) step to grant permissions. This alone is one
step too many to make it widespread -- I'd argue that even having to install an
app is too much.

To improve the user experience, some apps make emphasis on explaining how to use
their features. Others avoid it by trying to be smarter; they have your current
phone's usage data, so they already know which apps you use too much. One last
approach is to be opinionated and only support a subset of features that may
integrate better or have more impact. The Light Phone 2 does this by only
providing their limited list of features; if you're missing one, maybe you'll
get it, but maybe not.

Something else raising the barrier of entry is monetization. Although necessary,
some subscription models can be too much. A particularly creative app I liked
was {{< app name="Digital Detox" android="com.urbandroid.ddc" >}}, which makes
you pay $2 upon failing to meet your phone usage goals.

It's just great to have so many options and not being locked in to any of them.
Different solutions for different people.

=== Accessories

Some products allow you to disable apps based on physical access. Imagine a
keychain with an NFC chip that can restrict apps on your phone. Having to find
it and hold it near your phone can help break the habit of opening Instagram
automatically, turning it into a conscious decision. These tools can also help
transform your phone into a dumbphone: simply block the apps and leave the
device at home to fully disconnect.

A couple of options are https://getbrick.app/[Brick] and
https://www.unpluq.com/[UnPluq]. They only solve part of the issue, though, and
UnPluq follows a subscription-based model that costs 70€ per year. Still, they
seem to work well for some folks, which is awesome.

=== Phones

What would a phone minimizing screen time look like? Many of the popular ones
have https://en.wikipedia.org/wiki/Electronic_paper[_e-paper_ displays] instead
of LCD, which is most commonly seen on e-readers. E-paper feels like real paper,
is easier to see under sunlight, and may increase battery time. It doesn't come
without drawbacks, given that it literally moves physical particles in your
screen instead of emitting light. You can judge yourself:

++++
<iframe loading="lazy" width="1600" height="400" src="https://www.youtube.com/embed/IFgxUr26A8g" title="E ink phone | YouTube | Linus Tech Tips | Hisense A9" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
++++

Hey, it's not a good experience for videos, but it doesn't take 5 seconds per
refresh like your crappy 10-year-old Kindle. Knowing how it works under the
hood, this sample is impressive to me. Here's another monitor that recently came
out focusing on latency:

++++
<iframe loading="lazy" width="1600" height="400" src="https://www.youtube.com/embed/pXn-bAwzNv4?start=183" title="Modos Paper Monitor Status Update" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
++++

E-paper has always had a poor refresh rate. The issue isn't just that videos are
hard to watch -- you shouldn't do it often, anyway. The real problem is that
sluggish animations worsen the user experience. Recently, a wave of e-paper
products with faster refresh times&nbsp;<<daylight-zdnet>><<eink-glider>> has
emerged, so I'm hoping that will improve.

Another charasteristic of most e-paper screens is that they are grayscale. While
the absence of colors is linked with reduced
addiction&nbsp;<<grayscale-attention>>, it can also be frustrating. I've set my
phone to grayscale, and I know how confusing Google Maps can sometimes be
without colors. Additionally, charts that rely on color require you to view them
on a different device. And I haven't even tried gaming. One could argue that
this is intentional, to get you to use different devices for different purposes.
Instead of playing Candy Crush on the train, you might read and wait until you
get home to use your PS4.

There's now color e-paper, with Kobo having released its first e-readers in
2024&nbsp;<<kobo-color-eink>>. But it does have downsides, such as worse refresh
rates or lower contrast ratios. Personally, I'd love to try to embrace the
limitations of grayscale. Issues with essential apps like Google Maps could be
resolved with custom software. And not having the best experience watching
YouTube on your phone might be for good. It's possible that having a single
color like red could improve the user experience by highlighting important
items, though.

Nowadays, the biggest brands that go beyond e-readers are HiSense and Boox.
However, they aren't well-supported in the west. Some apps refuse to open, and
connectivity only works with certain providers, if at
all&nbsp;<<hisense-review>><<boox-connectivity>>. Boox is known for violating
GPL compliance, too&nbsp;<<boox-gpl>>. There are startups releasing similar
devices, but they have a long road ahead: Mudita will announce a new phone
soon&nbsp;<<mudita-release>>, and Daylight might work on a phone if their $729
tablet is successful&nbsp;<<daylight-release>><<daylight-podcast>>.

For 360€, the Blloc Zero18 was one of the few phones that didn't use e-paper but
wasn't a dumbphone either. It balanced full functionality with impressive
features designed to keep you from opening apps at all&nbsp;<<blloc-review>>. By
default, its screen was grayscale, but tapping the fingerprint sensor would
bring back the color. The homepage combined all your chats into a single feed,
similar to https://www.beeper.com/[Beeper], and had interactive widgets for
news, notes, or YouTube search. As you can tell from my use of the past sense,
though, they ended up ditching the phone. The company shifted focus to just
developing the launcher, and they ended up running out of
money&nbsp;<<blloc-dead>>. Many employees have since joined
https://intl.nothing.tech[Nothing].

Another notable flop&nbsp;<<yota-bankrupt>> was the
https://en.wikipedia.org/wiki/Yota[YotaPhone]. This unique phone featured an
additional e-paper screen on the back, marketed for reading and basic tasks. As
innovative as it was, you'd have to _really_ like reading to justify spending
over $600 for a phone that was otherwise unimpressive&nbsp;<<yota-2-review>>.
Unfortunately, it never gained popularity in Europe and was not released in the
US&nbsp;<<yota-1-eu>><<yota-2-eu>><<yota-crowd-fail>><<yota-3-fail>>.

A simpler approach to consider is what https://ghostmode.us/[Ghost Mode] does.
They lock down a Pixel&nbsp;6a with their custom operating system and resell it.
In the end, it's essentially a dumbphone with a nice camera. They don't need to
deal with manufacturing, and the software still has system access for advanced
features. I'm only afraid that relying on Google might not be a good
idea&nbsp;<<google-kills>>, but they could switch to a different base phone. Its
unpopularity might also have to do with money: at $600, it's pricey for a
dumbphone.

== Wrapping up

I hope this topic can eventually be "`a thing`". Just like there are movements
for "`sustainability`" or "`diversity`", there should also be one for "`reduced
screentime`". To me, it has a strong relationship with mental health, and
there's a lot to improve in that regard. I love the internet: being able to
share this post so easily is wonderful. But what can we do to reduce the bad
parts?

We still don't fully know what this hybrid between a smartphone and a dumbphone
looks like. However, this research has taught us many essential things: the
relevant organizations, its societal impact, how to build the company, existing
software and hardware solutions, and some history.

More details about the design will come later in
https://nullderef.com/series/dont-use-this-phone/[the series]. You can
https://nullderef.com/subscribe[subscribe] for free to keep up to date. It's
hard to say yet, but I'd love to build something in this area in the future.
Manufacturing a phone sounds crazy, but I'd love to see what can be done :)

_Disclaimer: I am not affiliated with any of the companies mentioned in this
post. The opinions expressed are my own and are based on my personal experiences
and research._

[bibliography]
== References

[.text-left]
- [[[light-phone-v1, 1]]]
  https://www.theverge.com/2019/9/4/20847717/light-phone-2-minimalist-features-design-keyboard-crowdfunding[The
  high hopes of the low-tech phone -- The Verge]
- [[[parking, 2]]]
  https://www.reddit.com/r/dumbphones/comments/sjtkm2/i_have_to_use_an_app_to_open_my_apartment_complex/[I
  have to use an app to open my apartment complex parking gate, the app is
  called Gatewise. My lease does not mention anything about needing a smartphone
  or the use of any apps for garage access. Street parking is not an option. I
  just want technological equity -- r/dumbphones]
- [[[nosurf-resources, 3]]]
  https://www.reddit.com/r/nosurf/comments/p73msh/digital_minimalism_reading_list/[Digital
  Minimalism Reading List -- r/NoSurf]
- [[[phone-depression, 4]]]
  https://www.wired.com/story/apple-investors-iphone-kids-depression-suicide-evidence/[Apple
  investors say iPhones cause teen depression. Science doesn't -- Wired]
- [[[bored, 5]]]
  https://www.youtube.com/watch?v=LKPwKFigF8U[Why Boredom is Good For You --
  YouTube, Veritasium]
- [[[bored-2, 6]]]
  https://www.youtube.com/watch?v=uuCoyILqut8[Louis CK Embrace Your Loneliness
  -- YouTube, The Impossible Conversation]
- [[[phones-sleep-filter, 7]]]
  https://arstechnica.com/gadgets/2021/05/iphones-night-shift-feature-doesnt-help-you-sleep-better-study-finds/[Study:
  Using Apple’s Night Shift to improve your sleep? Don’t bother -- arstechnica]
  (_Quote: "it is important to think about what portion of that stimulation is
  light emission versus other cognitive and psychological stimulations"_)
- [[[phones-crash, 8]]]
  https://www.nytimes.com/2024/01/26/health/cars-phones-accidents.html[Phones
  Track Everything but Their Role in Car Wrecks -- The New York Times] (_In
  summary, the exact number is unknown.
  https://www.prnewswire.com/news-releases/national-safety-council-estimates-that-at-least-16-million-crashes-are-caused-each-year-by-drivers-using-cell-phone
  s-and-texting-81252807.html[This NSC report] estimates it to be 1.6 million
  crashes, but it's not precise and from 2010_)
- [[[light-sensitivity-1, 9]]]
  https://ledstrain.org/[LEDStrain Forum]
- [[[light-sensitivity-2, 10]]]
  https://www.reddit.com/r/ChronicPain/comments/b936z9/has_anyone_here_been_diagnosed_with_central/[Has
  anyone here been diagnosed with central sensitization and/or relate somehow
  to my story? (36M, pain started at 33) -- r/ChronicPain]
- [[[gallup-survey, 11]]]
  https://news.gallup.com/poll/393785/americans-close-wary-bond-smartphone.aspx[Americans
  Have Close but Wary Bond With Their Smartphone -- Gallup]
- [[[basecamp, 12]]]
  https://37signals.com/[37signals (the company that owns Basecamp)]
- [[[basecamp-handbook, 13]]]
  https://basecamp.com/handbook[The 37signals Employee Handbook]
- [[[signalvnoise, 14]]]
  https://signalvnoise.com/[Signal v. Noise (37signals' former blog)]
- [[[calm-transistor, 15]]]
  https://www.reddit.com/r/SaaS/comments/nrjsao/im_40_years_old_and_i_finally_bootstrapped_a_saas/[I'm
  40 years old and I finally bootstrapped a SaaS, Transistor.fm, to millions in
  revenue (with a co-founder!) -- r/SaaS]
- [[[build-your-saas, 16]]]
  https://saas.transistor.fm/episodes[Build Your SaaS -- transistor.fm]
- [[[transistor-handbook, 17]]]
  https://github.com/TransistorFM/handbook/blob/master/values.md[What are our
  values? -- GitHub TransistorFM/handbook]
- [[[transistor-justin, 18]]]
  https://justinjackson.ca/[Justin Jackson (co-founder of Transistor.fm)]
- [[[wildbit, 19]]]
  https://wildbit.com/[Wildbit]
- [[[convertkit, 20]]]
  https://convertkit.com/handbook[The ConvertKit Team Handbook]
- [[[tristan-distraction, 21]]]
  https://www.youtube.com/watch?v=jT5rRh9AZf4[Distracted? Let's make technology
  that helps us spend our time well | Tristan Harris | TEDxBrussels -- YouTube,
  TEDx Talks]
- [[[couch-end, 22]]]
  https://www.inverse.com/input/features/rise-and-ruin-of-couchsurfing[Paradise
  lost: The rise and ruin of Couchsurfing.com -- Input]
- [[[basecamp-basic, 23]]]
  https://37signals.com/01[An obligation to independence -- 37signals (the
  company that owns Basecamp)]
- [[[nothing-money, 24]]]
  https://youtu.be/dDI9h4ool-E?t=1549[Nothing CEO Carl Pei on the Phone 2 and
  the future of gadgets | The Vergecast -- YouTube] @ 25:49
- [[[light-phone-money, 25]]]
  https://www.businessinsider.com/light-phone-2-dumb-phone-price-release-date-specs-2019-9[This
  credit-card-size phone can do only 3 things and doesn't have any apps — and it
  may be the key to freeing us from our smartphones -- Business Insider]
- [[[light-phone-igg, 26]]]
  https://www.indiegogo.com/projects/light-phone-2[Light Phone 2 -- IndieGoGo]
- [[[remarkable-money, 27]]]
  https://venturebeat.com/media/remarkable-raises-15-million-to-bring-its-e-paper-tablets-to-more-scribblers/[Remarkable
  raises $15 million to bring its e-paper tablets to more scribblers --
  VentureBeat]
- [[[mudita-funding, 28]]]
  https://archive.ph/4FODk[Mudita new technology company co-founder of CD
  Projekt -- eurogamer.pl (archive)]
- [[[openai, 29]]]
  https://openai.com/our-structure/[Our structure -- OpenAI]
- [[[apps, 30]]]
  Digital control:
    {{< app name="AppBlock" android="cz.mobilesoft.appblock" >}},
    {{< app name="Freedom" android="to.freedom.android2" ios="freedom-screen-time-control/id1269788228" >}},
    {{< app name="YourHour" android="com.mindefy.phoneaddiction.mobilepe" >}},
    {{< app name="Digital Detox" android="com.urbandroid.ddc" >}},
    {{< app name="StayFree" android="com.burockgames.timeclocker" >}},
    {{< app name="Stay Focused" android="com.stayfocused" >}},
    {{< app name="StayOff" android="com.app.floatingapptimer.com" >}},
    {{< app name="ActionDash" android="com.actiondash.playstore" >}},
    {{< app name="ClearSpace" ios="clearspace-reduce-screen-time/id1572515807" >}},
    {{< app name="Refocus" ios="refocus-app-website-blocker/id1645639057" >}},
    {{< app name="Opal" ios="opal-screen-time-for-focus/id1497465230" >}},
    {{< app name="Jomo" ios="jomo-screen-time-blocker/id1609960918" >}},
    {{< app name="SocialFocus: Hide Distractions" ios=socialfocus-hide-distractions/id1661093205" >}},
    {{< app name="UnTrap for YouTube" ios="untrap-for-youtube/id1637438059" >}},
    {{< app name="BB - Screen Time & App Blocker" ios="bb-screen-time-app-blocker/id6443657745" >}}
- [[[launchers, 31]]]
  Launchers:
    {{< app name="Olauncher" android="app.olauncher" >}},
    {{< app name="minimalist phone" android="com.qqlabs.minimalistlauncher" >}},
    {{< app name="Indistract" android="com.indistractablelauncher.android" >}},
    {{< app name="Blank Spaces" ios="blank-spaces-app/id1570856853" >}}
- [[[timers, 32]]]
  Productivity timers:
    {{< app name="Forest" android="cc.forestapp" >}},
    {{< app name="Flora" ios="flora-green-focus/id1225155794" >}},
    {{< app name="Plantie" ios="plantie-stay-focused/id1135988868" >}}
- [[[daylight-zdnet, 33]]]
  https://www.zdnet.com/article/daylight-debuts-worlds-first-blue-light-free-computer-with-a-120hz-livepaper-display/[
  Daylight debuts world's first 'blue-light-free computer' with a 120Hz
  LivePaper display -- ZDNET] (_Note: Daylight uses a mix between conventional
  electrophoretic e-paper and LCD. It feels slightly less like paper, but still
  improves refresh rate._)
- [[[eink-glider, 34]]]
  https://github.com/Modos-Labs/Glider["`Open-source Eink monitor with an
  emphasis on low latency`" -- GitHub Modos-Labs/Glider]
- [[[grayscale-attention, 35]]]
  https://www.theguardian.com/technology/2017/jun/20/turning-smartphone-greyscale-attention-distraction-colour[Will
  turning your phone to greyscale really do wonders for your attention? -- The
  Guardian]
- [[[kobo-color-eink, 36]]]
  https://www.theverge.com/2024/4/10/24124411/kobo-libra-colour-clara-colour-e-reader-kindle-e-ink[Kobo
  announces its first color e-readers -- The Verge]
- [[[hisense-review, 37]]]
  https://www.reddit.com/r/eink/comments/10hl3bv/hisense_a9_1_week_review/[Hisense
  A9 - 1 Week Review -- r/eink]
- [[[boox-connectivity, 38]]]
  https://help.boox.com/hc/en-us/community/posts/15815361554068-Why-oh-why-no-SIM-card-mobile-data-support[Why
  oh why no SIM-card / mobile data support? -- Boox Forums]
- [[[boox-gpl, 39]]]
  https://en.wikipedia.org/wiki/Onyx_Boox#GPL_Compliance[GPL Compliance, Onyx
  Boox -- Wikipedia]
- [[[mudita-release, 40]]]
  https://mudita.com/community/blog/introducing-mudita-kompakt/[First glimpse of
  Mudita Kompakt -- Mudita]
- [[[daylight-release, 41]]]
  https://www.theverge.com/2024/5/23/24163225/daylight-dc1-tablet-livepaper[The
  Daylight DC1 is a $729 attempt to build a calmer computer -- The Verge]
- [[[daylight-podcast, 42]]]
  https://youtu.be/2Y1nogFltPY?t=2240[Episode #234: Anjan Katta (Founder of
  Daylight Computer Co), by THE 2AM PODCAST -- YouTube] @ 37:20
- [[[blloc-review, 43]]]
  https://www.youtube.com/watch?v=31FrND2oqys[Android in Monochrome? | Blloc
  Zero 18 - exclusive first look]
- [[[blloc-dead, 44]]]
  https://discord.gg/NSJC3XcKaK[Blloc's Discord server] (more information in the
  _announcements_ channel)
- [[[yota-bankrupt, 45]]]
  https://www.theverge.com/2019/4/19/18508418/yota-devices-bankrupt-yotaphone[The
  company behind the dual-screen YotaPhone is bankrupt -- The Verge]
- [[[yota-2-review, 46]]]
  https://www.techradar.com/reviews/phones/mobile-phones/yotaphone-2-1228308/review[Yotaphone
  2 review -- TechRadar]
- [[[yota-1-eu, 47]]]
  https://www.pcmag.com/news/dual-screen-yotaphone-launches-in-russia-europe[Dual-Screen
  YotaPhone Launches in Russia, Europe -- PCMag] (_Release of first generation
  only in EU, Russia, and Middle East_)
- [[[yota-2-eu, 48]]]
  https://www.pcmag.com/news/dual-screened-yotaphone-2-launches-in-europe[Dual-Screened
  YotaPhone 2 Launches in Europe -- PCMag] (_Release of second generation only
  in EU, Russia, and Middle East_)
- [[[yota-crowd-fail, 49]]]
  https://www.androidpolice.com/2015/07/31/supply-issues-force-cancellation-of-north-american-yotaphone-2-despite-successful-crowdfunding-campaign/[Supply
  Issues Force Cancellation Of North American YotaPhone 2 Despite Successful
  Crowdfunding Campaign -- Android Police] (_Release failure of second
  generation in the US_)
- [[[yota-3-fail, 50]]]
  https://www.techradar.com/news/dual-screen-yotaphone-3-has-now-launched-and-its-as-odd-as-ever[Dual-screen
  YotaPhone 3 is finally official and it's just as kooky as the last two --
  TechRadar] (_Release of third and last generation only in China_)
- [[[google-kills, 51]]]
  https://killedbygoogle.com/[Killed by Google]
