---
title: "A phone designed not to be used: what would it take to build one?"
description: "TODO"
author: "Mario Ortiz Manero"
images: ["TODO"]
tags: ["tech"]
date: 2024-06-01
GHissueID: TODO
draft: true
---

What if there was a company selling phones that, against all odds, optimized how
_little_ they were used? Given that every company is trying to get you hooked
into their app, there's always so much more to be done here.

We have "https://en.wikipedia.org/wiki/Feature_phone[dumbphones]", for example.
These are phones whose functionality is intentionally locked down, with the
purest examples only supporting calls and SMS. On the other side of the
spectrum, we have smartphones. It wouldn't be far-fetched to say that most
people owning one use it more than they'd like.

I've seen people around me trying to switch to a dumbphone. It's not a bad idea;
it helps them reduce anxiety in the short term. But in the longer term, it turns
out to be impossible. Firstly, because some apps like WhatsApp or Lyft can be
indispensable for many. And secondly, because using most apps within reasonable
means are an improvement in quality of life. A GPS can be of immense help
getting around, or even watching Netflix to fight boredom in a plane.

And as a big fan of second-hand stuff, I'd rather give an old Motorola a second
life than bring yet another phone to the world. Plus, it'd be really cool to
open and close a retro flip-phone (right???). Even the founders of the Light
Phone -- arguably, the most popular dumbphone -- thought it was too much for
them, and they have released a more featureful version <<light-phone-v1>>.

Don't get me wrong! I admire the Light Phone and all the work they do. This is
such a small industry that anything helps. Lots of people out there are really
happy with their minimal phones, and that's great. But there may be something
that could become more mainstream; the lower the barrier of entry, the better.
And as always, I'm just trying to scratch my own itches.

So what if we tried to find a middle point? There are two possible approaches:

* A dumbphone trying to be a smartphone
* Or a smartphone trying to be a dumbphone

I'm a bigger fan of the latter, because most dumbphones don't run Android, and
it ends up being impossible to support everyone's use-cases one by one. Your
dumbphone's OS could add custom support for Uber, but there may be someone who
won't buy the phone unless it has Spotify. And a password manager. And their
banking app. After implementing all of these, someone will need a damned parking
app for their apartment complex <<parking>>. The mobile ecosystem is so huge
that it's very restrictive to start from nothing.

The question arises: how in the world would you manufacuture a phone? It sounds
like the most daunting task, especially given that I don't know anything about
hardware. Well, that's what I'll be doing some research about in this series! It
will cover topics like funding, studies about addiction, existing companies,
phone manufacturing, and more.

== Existing ideologies

Let's take a look at some similar projects and ideologies before anything else.

=== Calm Tech

"https://en.wikipedia.org/wiki/Calm_technology[Calm Technology]" is a design
concept that attempts to respect the user's attention.

=== Calm Companies

I strongly believe that in order to fund a company that cares about people's
mental health, the company itself must encourage the same for its workers. I
learned a lot about this by reading "It doesn't have to be crazy at work" from
the founders of Basecamp. It really makes you re-think

- It doesn't have to be crazy at work
  - Even if you don't want to work for a "calm company" or build one yourself,
    it'll teach you things.

Enterpreneurship is good for the world, so why not make it look better with
this?

== Founding principles

=== Ethics

I'm a big fan of bootstrapped companies instead of relying on VC money. I'm
afraid, however, that since I'm no billionaire, this won't be possible here.
Bootstrapping is doable if you're only working with software, but here we'll
need to pay for hardware (and a lot of it) before

Even crowdfunding might not help, because it's 

=== Technically-oriented

=== Privacy

In my experience, a big chunk of technically-oriented folks care about privacy.
Of course, we wouldn't be doing anything intentionally evil, but collecting
anonymous data can still be very helpful. The same way many companies run
experiments on how to increase app usage with A/B testing and similars, we'd
need something similar for the opposite. If we release this new feature, do
people actually unlock their phones less frequently?

"It doesn't have to be crazy at work"

=== Selling point

=== Strong community

It's important to open up some space to create a healthy community to discuss
these kind of things. It's a new-ish area, so people come in with lots of ideas.
I could imagine a list of features based on community votes like Spotify
(preferably, that's actually followed).

== Wrapping up

I hope this can eventually be "a thing". Just like there's conferences for
"bootstrapped companies" or sustainability, there should also be for better
digital control.

[bibliography]
== References

- [[[light-phone-v1, 1]]] https://www.theverge.com/2019/9/4/20847717/light-phone-2-minimalist-features-design-keyboard-crowdfunding[The high hopes of the low-tech phone -- The Verge]
- [[[parking,        2]]] https://www.reddit.com/r/dumbphones/comments/sjtkm2/i_have_to_use_an_app_to_open_my_apartment_complex/[I have to use an app to open my apartment complex parking gate, the app is called Gatewise. My lease does not mention anything about needing a smartphone or the use of any apps for garage access. Street parking is not an option. I just want technological equity -- Reddit]
