---
title: "A phone designed not to be used: what would it take to build one?"
description: "TODO"
author: "Mario Ortiz Manero"
images: ["TODO"]
tags: ["tech"]
series: ["dont-use-this-phone"]
date: 2024-06-01
GHissueID: TODO
// draft: true
---

What if there was a company selling phones that, against all odds, optimized how
_little_ they were used? Given that every company is trying to get you hooked
into their app, there's always so much more to be done here.

We have "https://en.wikipedia.org/wiki/Feature_phone[dumbphones]", for example.
These are phones whose functionality is intentionally locked down, with the
purest examples only supporting calls and SMS. On the other side of the
spectrum, we have smartphones. It wouldn't be far-fetched to say that most
people owning one use it more than they'd like.

I've seen people around me trying to switch to a dumbphone. It's not a bad idea;
it helps them reduce anxiety in the short term. But in the longer term, it turns
out to be impossible. Firstly, because some apps like WhatsApp or Lyft can be
indispensable for many. And secondly, because using most apps within reasonable
means are an improvement in quality of life. A GPS can be of immense help
getting around, or even watching Netflix to fight boredom in a plane.

And as a big fan of second-hand stuff, I'd rather give an old Motorola a second
life than bring yet another phone to the world. Plus, it'd be really cool to
open and close a retro flip-phone (right???). Even the founders of the Light
Phone -- arguably, the most popular dumbphone -- thought it was too much for
them, and they have released a more featureful version <<light-phone-v1>>.

Don't get me wrong! I admire the Light Phone and all the work they do. This is
such a small industry that anything helps. Lots of people out there are really
happy with their minimal phones, and that's great. But there may be something
that could become more mainstream; the lower the barrier of entry, the better.
And as always, I'm just trying to scratch my own itches.

So what if we tried to find a middle point? There are two possible approaches:

* A dumbphone trying to be a smartphone
* Or a smartphone trying to be a dumbphone

I'm a bigger fan of the latter, because most dumbphones don't run Android. Given
how huge the mobile ecosystem is, it ends up being very restrictive to support
everyone's use-cases one by one. Your dumbphone's OS could add custom support
for Uber, but there may be someone who won't buy the phone unless it has
Spotify. And a password manager. And their banking app. And after implementing
all of these, someone will need a damned parking app for their apartment complex
<<parking>>.

The question arises: how in the world would you even manufacuture a phone? It
sounds like the most daunting task, especially given that I don't know anything
about hardware. Well, that's what I'll be doing some research about in this
series! We'll cover topics like funding, studies about addiction, existing
companies, phone manufacturing, and more.

== Looking at the current state

I've been drawn to this space for some time, trying to learn from existing
solutions and see what people are coming up with:

=== Technology

Firstly, let's take a step back from "phones that shouldn't be used". Can we
generalize it to "tech that shouldn't be used"? Or rather, "tech that doesn't
unnecessarily grab your attention"? Well, then you'd be onto something! That's
precisely the definition of "https://en.wikipedia.org/wiki/Calm_technology[Calm
Technology]".

This is very centered around _design_, but still very much in our area.

=== Companies

In order to start a company that cares about people's mental health, it's
sensible to say that its workers shouldn't be crunching 60 hours per week. Most
of my learnings here come from reading "It doesn't have to be crazy at work",
written by the founders of Basecamp.

The book makes you re-think many things you take for granted about how companies
are built. Leadership, benefits, planning, hiring, funding... And in which ways
one can make it more sane overall.

If you start a company by thinking you'll
change the world, the stakes will be higher from the start.

"We won't get rich".

This would build on top of the naïve assumption that the less screen time, the
better off the company is.

Enterpreneurship is good for the world, so why not make it look better with
this?

I plan on another article just about this.

=== Software

Most phones actually come with excellent features to minimize screen time. But
they don't seem to be enough because of two reasons:

1. They aren't well marketed; most people aren't aware of their existence.
   Android calls them "https://www.android.com/digital-wellbeing/[Digital
   Wellbeing]", but I personally receive more system notifications about new AI
   features in my camera than things like this.
2. They aren't first-party citizens; the tools are there, but they don't quite
   integrate seamlessly. The most powerful feature on Android is "modes", which
   allows one to configure parts of your phone based on triggers or manually.
   For example, when your GPS is in the library, disable Instagram and set the
   phone to grayscale. Being so powerful, it's also complicated to configure,
   though. If the company was optimizing for less screen time instead of ad
   revenue, we'd surely have more ideas to improve its adoption.

TODO: too many permissions makes you concerned about the phone's security

Pulling off a solution that's fully software-based can be complicated; it often
needs cooperation with hardware. For instance, the open-source app
https://timelimit.io/[TimeLimit.io] is an even more configurable alternative to
"Digital Wellness". Unfortunately, it starts with a step to grant permissions,
which is one step too many to make it widespread. I'd argue that even having to
install it is too much.

There are alternatives exceeding the million downloads and better usability,
although their source code isn't available:

* Digital control
** [Android] https://play.google.com/store/apps/details?id=cz.mobilesoft.appblock[AppBlock]
** [Android, iOS] https://play.google.com/store/apps/details?id=to.freedom.android2[Freedom]
** [Android] https://play.google.com/store/apps/details?id=com.mindefy.phoneaddiction.mobilepe[YourHour]
** [Android] https://play.google.com/store/apps/details?id=mrigapps.andriod.breakfree.deux[SPACE]
** [Android] https://play.google.com/store/apps/details?id=com.urbandroid.ddc[Digital Detox]
** [Android, iOS] https://play.google.com/store/apps/details?id=com.burockgames.timeclocker[StayFree] (iOS version might be crap)
** [Android, iOS] https://play.google.com/store/apps/details?id=com.stayfocused[Stay Focused]
** [Android] https://play.google.com/store/apps/details?id=com.app.floatingapptimer.com[StayOff]
** [Android] https://play.google.com/store/apps/details?id=com.actiondash.playstore[ActionDash]
** [iOS] https://apps.apple.com/us/app/clearspace-reduce-screen-time/id1572515807[ClearSpace]
** [iOS] https://apps.apple.com/us/app/refocus-app-website-blocker/id1645639057[Refocus]
** [iOS] https://apps.apple.com/us/app/opal-screen-time-for-focus/id1497465230[Opal]
* Launchers
** [Android] https://play.google.com/store/apps/details?id=com.qqlabs.minimalistlauncher[minimalist phone]
** [Android] https://play.google.com/store/apps/details?id=com.indistractablelauncher.android[Indistract]
** [iOS] https://apps.apple.com/us/app/blank-spaces-app/id1570856853[Blank Spaces]
** [iOS]
* Productivity timers: even gamified
** [Android, iOS] https://play.google.com/store/apps/details?id=cc.forestapp[Forest]
** [iOS] https://apps.apple.com/us/app/flora-green-focus/id1225155794[Flora]
** [iOS] https://apps.apple.com/us/app/plantie-stay-focused/id1135988868[Plantie]

I haven't used all of them, so comment your experiences!

There's a conflict in monetizing this kind of software, where you'd need to
serve ads or make purchasable content.

TODO: it's also harder to monetize

=== Accessories

Some products make it possible to disable apps based on physical access to them.
Requiring NFC to unblock apps can help you avoid the reflex of opening Instagram
automatically, making it a conscious choice. There's also the option of blocking
the apps and leaving the device at home to fully disconnect.

A couple of them include https://getbrick.app/[Brick] and
https://www.unpluq.com/[UnPluq]. They only solve part of the problem, though,
and UnPluq follows a subscription-based model for 70€ per year. Regardless, they
seem to work well for some people, which is awesome.

=== Phones

A common pattern is the usage of EInk displays. EInk is commonly seen on
e-readers, as an alternative that TODO. And it turns out that its
performance can be much better than your crappy Kindle, which takes 5 seconds to
skip to the next page. There's even now color EInk, with Kindle releasing its
first version in 2014 [TODO: link].

TODO: VIDEO

Some of the most popular brands are HiSense and Boox. However, they aren't that
well marketed nor supported outside of Asia. There are also some new startups
catching up releasing new devices, such as Mudita or Daylight, but they aren't
quite there yet. Anyhow, I plan on diving deeper into this in a later article.

== Wrapping up

I hope this can eventually be "a thing". Just like there's conferences for
"bootstrapped companies" or sustainability, there should also be for better
digital control.

[bibliography]
== References

- [[[light-phone-v1, 1]]] https://www.theverge.com/2019/9/4/20847717/light-phone-2-minimalist-features-design-keyboard-crowdfunding[The high hopes of the low-tech phone -- The Verge]
- [[[parking,        2]]] https://www.reddit.com/r/dumbphones/comments/sjtkm2/i_have_to_use_an_app_to_open_my_apartment_complex/[I have to use an app to open my apartment complex parking gate, the app is called Gatewise. My lease does not mention anything about needing a smartphone or the use of any apps for garage access. Street parking is not an option. I just want technological equity -- Reddit]
