---
title: "A phone designed not to be used: how to set up the company?"
description: "TODO"
author: "Mario Ortiz Manero"
images: ["TODO"]
tags: ["tech"]
series: ["dont-use-this-phone"]
date: 2024-06-01
GHissueID: TODO
draft: true
---

TODO: merge with "startup/index.adoc"

TODO general

- https://en.m.wikipedia.org/wiki/Douglas_Engelbart
- https://news.ycombinator.com/item?id=32315701 (effective altruism)
- https://www.breakneck.dev/blog/no-tech-cofounder and https://news.ycombinator.com/item?id=39904704
- Calm Companies: Balsamiq, Transistor.fm, Wildbit, Convertkit
- https://longform.asmartbear.com/avoid-blundering/
- https://news.ycombinator.com/item?id=40654190
- Funding: https://calmfund.com/writing/pause
- https://www.outseta.com/posts/calm
- https://www.indie.vc/ (had a similar model to Calm Fund, also shut down shop for a while due to capital constraints. They've since restarted the fund though)
- https://newsletter.rhizomerd.com/p/when-to-design-for-emergence ("But what if someone does it before you"? There doesn't have to be a single solution to this. Especially considering how huge the opposing market (those who want you to be staring at the phone) is, and how many ways there are to avoid it.)

TODO non-profits

- https://adoptaunabuelo.org/una-carta-para-un-abuelo/

TODO: open source

- https://twitter.com/m_ou_se/status/1438946869447692297
- https://www.reddit.com/r/rust/comments/pub2mq
- https://www.lunasec.io/docs/blog/how-to-build-an-open-source-business-in-2021-part-1/
- https://vadimdemedes.com/posts/generating-income-from-open-source
- Inspiration: Typst, Kagi, Proton, Antithesis
- Funding: OSS Capital
- https://codecodeship.com/blog/2023-04-14-mike-perham
- https://docs.emailengine.app/how-i-turned-my-open-source-project-into/
- https://anonymoushash.vmbrasseur.com/2018/08/24/open-source-is-not-a-business-model-and-your-business-will-fail-if-you-think-that-it-is/
- Note: Licensing is easy with B2B because piracy is much less popular

== Founding principles

=== Ethics

I'm a big fan of bootstrapped companies instead of relying on VC money. I'm
afraid, however, that for hardware manufacturing this would only be viable for
billionaires. Here we'll need to pay for hardware (and a lot of it) before
receiving a cent from customers.

Even crowdfunding might not help, because it's

=== Technically-oriented

=== Privacy

In my experience, a big chunk of technically-oriented folks care about privacy.
Of course, we wouldn't be doing anything intentionally evil, but collecting
anonymous data can still be very helpful. The same way many companies run
experiments on how to increase app usage with A/B testing and similars, we'd
need something similar for the opposite. If we release this new feature, do
people actually unlock their phones less frequently?

"It doesn't have to be crazy at work"

=== Selling point

=== Strong community

It's important to open up some space to create a healthy community to discuss
these kind of things. It's a new-ish area, so people come in with lots of ideas.
I could imagine a list of features based on community votes like Spotify
(preferably, that's actually followed).

[bibliography]
== References

- [[[TODO, 1]]] TODO
