---
title: "The Endless Pursuit of Building Companies that Don't Suck"
description: "My research on founding startups in a sustainable way, from all the possible perspectives."
author: "Mario Ortiz Manero"
images: ["TODO"]
tags: ["tech"]
date: 2024-01-07
GHissueID: TODO
draft: true
---

_I'll preface this by saying that I have no idea what I'm talking about. The
point, in fact, is to learn, think, and share my findings. This is a very
personal life journey, but I'm sure everyone can relate to some parts and take
something out of it._
aas

== Not sucking...

I only use the term "not sucking" because setting a higher bar would be
overreaching, given the complexity of the problem. Let's get into specifics:

=== from an ethical perspective

It's extremely objective to say how "good" or "bad" a company is. Of course, it
should be at least "neutral" according to your beliefs. There must always be
people keeping the world running, and one can find lots of personal satisfaction
from a restaurant or even a SaaS.

You could go a step further and try to directly improve the world! There are
many things broken, so you'll have plenty to choose from. Try to find your most
relevant one: plastic waste, ocean biodiversity, mental health... It doesn't
even need to be a brilliant idea because there's so much missing execution out
there.

=== from an organizational perspective

An open question I have is whether scale eventually dehumanizes companies. Most
examples I've found so far are smaller ones. How do you prevent all of this from
fading away as it starts to grow? I don't think this is important at the very
beginning, though.

=== from a personal perspective

Starting a company sounds like something that could take over your life. Even if
you're fulfilled by your work, you don't want to lose other aspirations, such as
travelling, time with loved ones, or hobbies. I've personally seen way too many
people trapped by their profession, bleeding into their own life, and others'.

=== from a financial perspective

Unfortunately, many major problems in the world aren't easy to fund.

==== Startup accelerators

Programs like Y Combinator provide a service that sounds like a "startup
school". You get some funding from them and a ton of resources to actually get
started. They even support nonprofits!

However, much of the work here is related to external investing. Asking for
money will increase the pressure on you to provide greater returns, which
doesn't help. It may make you more stressed, or make your company deviate from
its original purpose.

Although required in many capital-intensive companies, it shouldn't be the
"default choice". Funding in this can be like strapping a rocket to your
company; it will grow immensely and then crash when it runs out of fuel.
Ideally, we'd like something more linear that grows over time sustainably.

==== Nonprofits

A nonprofit's objective is to provide a collective, public or social benefit, as
opposed to an entity that operates as a business aiming to generate a profit for
its owners.

In the US, there are many kinds of nonprofits: Public Charities (501(c)(3)),
Social Welfare Organizations (501(c)(4)), Labor/Agricultural Organizations
(501(c)(5)), Business Leagues (501(c)(6)), and Social Clubs (501(c)(7)). I'll be
mostly focusing on Private Foundations (501(c)(3)).

There's also the possibility of having a mixed structure like OpenAI's infamous
one. They started as a 501(c)(3), but after only raising $150M out of their $1B
goal, they switched to a "capped for-profit" structure. This introduced a new
for-profit company that is fully owned by the non-profit, but that still can
distribute equity. Investments whose returns exceed the 100x cap must be donated
to their cause, which will supposedly be nothing compared to the profits an AGI
would generate.

==== Crowdfunding

==== Social enterprises

==== For-profits

There are some ways in which a for-profit can try to prove they're sustainable.
Some of these depend a lot on local laws, but I've included some examples from
the US:

* The "B Corporation" certificate is granted only to for-profit companies with a
  good enough social impact and environment performance. The commitments must be
  integrated into stakeholders and company-governing documents, and an annual
  fee based on annual sales must be paid. Re-certification is necessary every
  three years.
* A "[benefit corporation](https://en.wikipedia.org/wiki/Benefit_corporation)"
* There's also "[low-profit limited liability
  companies](https://en.wikipedia.org/wiki/Low-profit_limited_liability_company)"
  (L3C).
* https://en.wikipedia.org/wiki/Social_purpose_corporation
* https://en.wikipedia.org/wiki/Sustainable_business

== My journey

Software engineering has always brought me lots of joy from the technical
standpoint. It's weird, but building and fixing systems is fun to me. Recently,
though, I've started to have this itch that I need something which makes me
proud of my work longer term. To me, working on your own thing is what really
ensures you'll be proud of it, as you're not as controlled by other people's
ideas. And sure, my systems are shiny and cool, but what's in it for the world?

I'm lucky enough to believe I have the choice to do something about this. It
feels like the hardest thing I'd do in my life and requires time and experience,
though. So I need to take it slow, and continue to learn from working for
others. In the meanwhile, I can try to learn a bit more about how I could ever
do it.

There's also paths to achieve this "long-term satisfaction about your work".
It's important to consider them before, you know, incorporating a company.

=== Side jobs

One of my worries is forcing myself to a passion that's not really mine just for
this. Becoming a CEO is something that technically attracts me less, and that I
feel less talented for. In order to truly be effective, I need to find something
that fully utilizes my resources.

Voluntary work.

=== Effective altruism

Working on whatever and donating to a cause.

There needs to be a combination of working on what you are most effective on,
and doing so for a good cause. And sometimes, that just isn't there. TODO:
example.

== References

=== Jen-Hsun Huang -- NVIDIA

Original video: https://www.youtube.com/watch?v=Xn1EsFe7snQ

- VC don't invest in business plans, it does in people and the market. The
  latter isn't so important because it changes, and you need to reinvent
  yourself. He started with $2M.
- Initial plan was to build chips for 3D gaming; first in the market.
- Perspective > vision. Everyone has it, just specific to yourself,
  surroundings, tastes, etc. Perspective > ideas.
- What's the essence of your business? What makes it work?
- Ignored customers for 5Y to create the industry.
- Why do you want to build a company? I hope it's not money.
- Company growth -> you have to take the initiative to cannibalize your own
  products. Otherwise, someone else will.
- Fail to learn, but fail quickly, "intellectual honesty".
- CEO skill: Become comfortable with ambiguity
- Started at 30yo, no business classes prior
- He learns from anybody (even kids)
- Focus; do one thing well
- Everything is torn apart & reinvented @ some point

- Pending questions: relationships with kids, burnout, working too much?? He
  only seems to work

=== Jason Fried -- 37 Signals (Basecamp)

https://open.spotify.com/episode/2bOWmObaUPcx23lw0RDgs7?si=mj6KdaStRQ6COLkbEnLRgQ

More info: https://37signals.com/

Life motto: worry less 

Made profit over 24y, over the last 10y $X0M, around 100k+ customers. 75 employees. Extremely opinionated towards efficiency and simplicity.

Bootstrapping
- VC when you need a big initial investment. Not so important for software. Also for big scale requirements like Airbnb or Uber (there needs to be one everywhere, note that they aren't pure software either)

Efficiency
- Only focus on a single product. No customization, customer support. Stick-Shift, bare business.
- ShapeUp framework: New products built by 2 people, 1 programmer and 1 designer/product given 2-6 weeks. If it's more, give it 2 more days if almost there, or kill it. Long-term Business planning/promises is bad, such as "by EOY". You can't "Sprint" back to back (plus same thing all the time gets boring), so they do a 2w cool down cycle afterwards to freelance internally (fixing stuff, messing around with things, shaping up projects, etc).
- Don't spend money on stuff you don't need.
- success = wanting to do it again
- not looking at profitability per product or more stats like OKR, growth targets, etc, just overall profitability 
- no investors, board, intentions to sell

- intuition driven instead of data. Experience over data or charts.
- hard to apply for others in the company, so they ask themselves "how do you feel" or "what do you think" instead of "what do you know". We're not after certainty.
- he applies the same on failure. Since they don't know what went wrong, he doesn't look back that much.
- how to bootstrap people with not enough experience?
- they pay interviewees to do project. He asks what they'd do with more time, so it's based on instinct.

- large changes quickly are bad, such as migration to scale up directly.
- he thought it'd be great to have one single project, but they actually had more ideas and also made Hey and Once.
- doesn't like words for war for business like workforce, target customers, etc
- to get started, stay as small as you can for as long as you can. Do it yourself. That way you can control your costs, which should be as low as possible.

Once (idea, but not proven): non-SaaS products, you pay and install them, under $1000. No fees or subscription, and they still get updates and support. Costs are very low because there's no hosting. Opportunity: many alternatives for one product, by they still charge luxury prices.


Recommended books: Finite and infinite games, several short sentences about writing, hell yeah or no, home-made contemporary Russian folk artifacts 

* Remaining questions: personal life??

=== It doesn't have to be crazy at work - Jason Fried

Basecamp. Intentional decisions to make a calm company. Meetings only as the last resort, no late working, reasonable expectations/deadlines, no untilimited growth, funding comes from customers rather than VC.

No fighting with other companies to win marketshare. In fact, not caring about marketshare, just profits > expenses, and some growth in profits if possible. Focus on the product.

Apart from the two above, no goals. Leaving some money on the table is okay. More specific/quarterly goals are arbitrary and stressful. It also leads to companies compromising their morals when trying to achieve them.

Short-term planning (e.g., every 6 weeks instead of "5 year plan") is more flexible. It also doesn't instill a fake sense of security. If a deadline won't be met, reduce scope. Don't ship on Fridays. But make it very strict to avoid stress and ambiguity. Feedback on new projects requires time and thought, rather than just reacting after a presentation about it.

Employee attention and focus is most important. They don't have status meetings and instead share it async, for example. Don't be busy for the sake of it, either (getting obsessed with productivity). The team lead sends a monthly update to the company ("Heartbeat"), only with details they need to know.

They rely on established office hours to answer questions or help (especially subject experts in the company). Can be from Tuesday afternoons to an hour. Most questions can wait. Scheduling time with someone is intentionally hard; calendars are set as private. Availability isn't expected of anyone, because most things can wait anyway. Emergencies are 1% and shouldn't dictate the other 99.

Trying to change the world with the company is unsustainable. It makes it easy to justify late meetings or bad practices. If you do change it, it's not because you said you would.

No personal attachment from employees ("we're a family") or founders ("X is our baby"). People have time with friends and family outside work anyway. The company should support that instead.

Leadership has a huge influence on the team. They shouldn't be overworking. They should also not expect people will reach out to them about issues. Instead, ask for feedback (and not easy one). Only do so when you're able to act on the feedback.

As a leader, try to avoid making small suggestions or asking about stuff like "How is Instagram going?", because its importance will be overstated. It's another source of distraction.

The further away you are from a "low-hanging fruit", the lower it looks.

Shopify's "trust battery": dictates whether a relationship between two people is well. Otherwise, it results in people exploding. Human relationships also need to be maintained at work.

They hire people for their work, not their CV. Final candidates are hired for a week and given $1500 to actually see how they work. Company needs to be open about talent (location, diversity, studies), and employees need to be good persons. No expectation after hiring that they are super efficient.

Fixed salary per level and role. Adjusted to be top 10% of industry. Raises based on that, no decreases. They use consulting to get the data. No bonuses and no stock options because of no intention of selling the company. And if they did, fixed percentage of sell price goes to employees. Fixed part of profits also go to employees, regardless of role.  Requirement to say why people leave to avoid assumptions and gossip.

Benefits to keep people out of the office, not inside of it. Also, 3 weeks of vacations without being pending of work. Some flexibility if more are needed.
- Fully paid vacation per year, $5000 per family
- Three-day weekends in summer
- 30d paid sabaticals every 3y
- $1000/y for education, especially stuff outside work like instruments
- $2000/y charity match
- Monthly massage at spa
- $100/no for fitness

Office with library rules to avoid interruption and keep it quiet.

Actively avoid bad situations (e.g., bad-calling other companies), don't let them slip. Otherwise they'll become the norm.

Open questions:
- What to do w.r.t. funding if it's s capital-intensive business? Unlike Basecamp, which is full software
- How to approach social live within work? No meetings means less business but also less interaction. Especially with a remote company.
- Slow food movement?
- How to do onboarding if it's all async? What's the process?
- What happens in emergencies during vacation?
- How to deal with completely opposite timezones for async?
- You require people to spend a week working on a paid project before hiring them. What if they already have a job?
- How do you approach promotions and people only focusing on that (impact)?

=== Links

- https://twitter.com/m_ou_se/status/1438946869447692297
- https://www.reddit.com/r/rust/comments/pub2mq
- https://www.lunasec.io/docs/blog/how-to-build-an-open-source-business-in-2021-part-1/
- https://vadimdemedes.com/posts/generating-income-from-open-source
- https://typst.app/
- https://kagi.com/
- https://proton.me/
- https://adoptaunabuelo.org/una-carta-para-un-abuelo/
- https://www.linkedin.com/posts/lennyrachitsky_37signals-is-a-very-different-kind-of-company-activity-7142214613126840320-vo8F?utm_source=share&utm_medium=member_android
- https://wavepaths.com/
- https://codecodeship.com/blog/2023-04-14-mike-perham
