---
title: "The Endless Pursuit of Building a Business that Doesn't Suck"
description: "Some investigation on how to found a startup in a sustainable way"
author: "Mario Ortiz Manero"
images: ["TODO"]
tags: [TODO]
date: 2024-01-07
GHissueID: TODO
draft: true
---

I'll preface this by saying that I have no idea what I'm talking about. The
point, in fact, is to learn, think, and share my findings. This is a very
personal life journey, but I'm sure everyone can relate to some parts and take
something out of it.

== Rationale

This whole article stems from a feeling of not having a deeply rewarding
professional life as a software engineer. From a technical standpoint, it does
bring me immense joy; building systems makes passionate and engaged in my work.
But there's always an itch on how I could be working on something that directly
improves the world instead. And I'm lucky enough to be in an industry where I do
have the choice. The market is good enough that if I wanted, I could be doing
it. So what's stopping me?

One thing to note is that this isn't something I've always been thinking about,
but rather recent. Furthermore, I believe that achieving the expectations that
I'm setting myself is one of the toughest things I'd do in my life. Doing it
right would require abundant time and experience, so rather than being in a
hurry, it's a very long term objective. I want to have time for experimentation
and reasoning before jumping to anything, which is why there might be too much
investigation instead of jumping into practice, which is what I would usually
do.

== Not sucking

Why do I use the term "sucking"? Because setting a higher bar than that would be
setting it too high, given the complexity of the problem. The only exception I'm
making is the source of the problem: the ethics. In that case, "not sucking"
would mean that my job would be neutral to the world, and I'm explicitly looking
for something positive.

=== From an ethical perspective

At the same time, it's my impression that doing this could possibly take over my
life. Even if I want to improve the world, I still have other aspirations that I
don't want to lose: travelling, time with loved ones, and other interests. I've
seen too many people trapped in their professional life, bleeding into the
personal one.

There are many things broken in the world to choose. In my case, personal
livings make mental health the most interesting one to me.

Ideas:

* Either directly about mental health, or donating all profits to it
  * What things make the most money that could be invested?
* How do nonprofits work
* Look into OpenAI, Mozilla, the mind wellness platform from Lyft

https://80000hours.org/career-reviews/software-engineering/

Crazy ideas:

=== From an organizational perspective

One of my worries is forcing myself to a passion that's not really mine just for
this. Becoming a CEO is something that technically attracts me less, and that I
feel less talented for. In order to truly be effective, I need to find something
that fully utilizes my resources.

=== From a personal perspective

* Scale dehumanizes companies?
* Keeping it small could make it more manageable?

An alternative would be "Effective Altruism", where I just work for something
lucrative that's not good for the world, but donate most of the earnings for a
good cause.

Unrelated fun business ideas:

* kebab-style sushi
* bartender drink recommendation system

=== From a financial perspective

Unfortunately, many major problems in the world aren't easy to fund.

== Methods

=== Starting with what you want to improve

E.g., becoming an expert in something if you want to improve that. Aligns with
"you're 2/3s of your best friends/environment".

Downsides: you might not enjoy working in that area yourself.

=== Career change

Working on whatever to fund your basic expenses and work on something else that
needs improvement but doesn't have that much funding.

=== Effective Altruism

Working on whatever and donating to a cause.

There needs to be a combination of working on what you are most effective on,
and doing so for a good cause. And sometimes, that just isn't there. TODO:
example.

== References

=== Jen-Hsun Huang -- NVIDIA

Original video: https://www.youtube.com/watch?v=Xn1EsFe7snQ

- VC don't invest in business plans, it does in people and the market. The
  latter isn't so important because it changes, and you need to reinvent
  yourself. He started with $2M.
- Initial plan was to build chips for 3D gaming; first in the market.
- Perspective > vision. Everyone has it, just specific to yourself,
  surroundings, tastes, etc. Perspective > ideas.
- What's the essence of your business? What makes it work?
- Ignored customers for 5Y to create the industry.
- Why do you want to build a company? I hope it's not money.
- Company growth -> you have to take the initiative to cannibalize your own
  products. Otherwise, someone else will.
- Fail to learn, but fail quickly, "intellectual honesty".
- CEO skill: Become comfortable with ambiguity
- Started at 30yo, no business classes prior
- He learns from anybody (even kids)
- Focus; do one thing well
- Everything is torn apart & reinvented @ some point

- Pending questions: relationships with kids, burnout, working too much?? He
  only seems to work

=== Jason Fried -- 37 Signals (Basecamp)

https://open.spotify.com/episode/2bOWmObaUPcx23lw0RDgs7?si=mj6KdaStRQ6COLkbEnLRgQ

More info: https://37signals.com/

Life motto: worry less 

Made profit over 24y, over the last 10y $X0M, around 100k+ customers. 75 employees. Extremely opinionated towards efficiency and simplicity.

Bootstrapping
- VC when you need a big initial investment. Not so important for software. Also for big scale requirements like Airbnb or Uber (there needs to be one everywhere, note that they aren't pure software either)

Efficiency
- Only focus on a single product. No customization, customer support. Stick-Shift, bare business.
- ShapeUp framework: New products built by 2 people, 1 programmer and 1 designer/product given 2-6 weeks. If it's more, give it 2 more days if almost there, or kill it. Long-term Business planning/promises is bad, such as "by EOY". You can't "Sprint" back to back (plus same thing all the time gets boring), so they do a 2w cool down cycle afterwards to freelance internally (fixing stuff, messing around with things, shaping up projects, etc).
- Don't spend money on stuff you don't need.
- success = wanting to do it again
- not looking at profitability per product or more stats like OKR, growth targets, etc, just overall profitability 
- no investors, board, intentions to sell

- intuition driven instead of data. Experience over data or charts.
- hard to apply for others in the company, so they ask themselves "how do you feel" or "what do you think" instead of "what do you know". We're not after certainty.
- he applies the same on failure. Since they don't know what went wrong, he doesn't look back that much.
- how to bootstrap people with not enough experience?
- they pay interviewees to do project. He asks what they'd do with more time, so it's based on instinct.

- large changes quickly are bad, such as migration to scale up directly.
- he thought it'd be great to have one single project, but they actually had more ideas and also made Hey and Once.
- doesn't like words for war for business like workforce, target customers, etc
- to get started, stay as small as you can for as long as you can. Do it yourself. That way you can control your costs, which should be as low as possible.

Once (idea, but not proven): non-SaaS products, you pay and install them, under $1000. No fees or subscription, and they still get updates and support. Costs are very low because there's no hosting. Opportunity: many alternatives for one product, by they still charge luxury prices.


Recommended books: Finite and infinite games, several short sentences about writing, hell yeah or no, home-made contemporary Russian folk artifacts 

* Remaining questions: personal life??

=== Links

- https://twitter.com/m_ou_se/status/1438946869447692297
- https://www.reddit.com/r/rust/comments/pub2mq
- https://www.lunasec.io/docs/blog/how-to-build-an-open-source-business-in-2021-part-1/
- https://vadimdemedes.com/posts/generating-income-from-open-source
- https://typst.app/
- https://kagi.com/
- https://proton.me/
- https://adoptaunabuelo.org/una-carta-para-un-abuelo/
- https://www.linkedin.com/posts/lennyrachitsky_37signals-is-a-very-different-kind-of-company-activity-7142214613126840320-vo8F?utm_source=share&utm_medium=member_android
- https://wavepaths.com/
- https://codecodeship.com/blog/2023-04-14-mike-perham
