---
title: "The bane of my existence: Supporting both async and sync code in Rust"
description: "Sit beside me and hear this crazy old man's tale of when I asked
Rust for too much"
author: "Mario Ortiz Manero"
tags: ["rust", "async", "macros"]
date: 2021-09-15
GHissueID: 20
---

== Introduction

Imagine you want to create a new library in Rust. All it does is wrap up a
public API that you need for something else, like
https://developer.spotify.com/documentation/web-api/[the Spotify API] or maybe a
database like https://www.arangodb.com/[ArangoDB]. It's not rocket science, you
aren't inventing something new or dealing with complex algorithms, so you expect
it to be relatively straightforward.

You decide to implement the library with async. Most of the work in your library
has to do with performing HTTP requests, which are mostly I/O, so it makes sense
(that, and because it's what the cool kids use in Rust nowadays). You start
coding and have the v0.1.0 release ready in a few days. "`Neat`", you say as
`cargo publish` finishes successfully and uploads your work to
https://crates.io[crates.io].

A couple days pass and you get a new notification on GitHub. Someone opened an
issue:

____
*How can I use this library synchronously?*

My project doesn't use async because it's overly complex for what I need. I
wanted to try your new library, but I'm not sure how to do it easily. I would
rather not fill my code with `block_on(endpoint())`. I've seen crates like {{<
crate reqwest >}} exporting a
https://docs.rs/reqwest/0.11.4/reqwest/blocking/index.html[`blocking` module]
with the exact same functionality, could you perhaps do that as well?
____

Now, low-level wise that sounds like a very complicated task. Having a common
interface for both async code -- which requires a runtime like {{< crate tokio
>}}, awaiting futures, pinning, etc -- and regular sync code? I mean, they asked
nicely, so maybe we can try. After all the only difference in your crate would
be the occurrences of the `async` and `await` keywords because you aren't doing
anything fancy.

Well, this is _more or less_ what happened with the crate {{< crate rspotify
>}}, which I maintain along with its creator
https://github.com/ramsayleung/[Ramsay]. For those who don't know, it's a
wrapper for the Spotify Web API. Did we get this working in the end? If so, how?
I'll try to explain the situation in this article.

== The first approaches

To put the reader more into context, here's what Rspotify's client looks like,
more or less:

[source, rust]
----
struct Spotify { /* ... */ }

impl Spotify {
    async fn some_endpoint(&self, param: String) -> SpotifyResult<String> {
        let mut params = HashMap::new();
        params.insert("param", param);

        self.http.get("/some-endpoint", params).await
    }
}
----

Essentially, we would have to make `some_endpoint` available for both
asynchronous and blocking users. The important question here is, how do you do
this once you have hundreds of endpoints? And how can you make it easy to switch
between async and sync for the user?

=== Good ol' copy-pasting

This is what was first implemented. It was quite simple and it worked. You just
need to copy the regular client code into a new
https://github.com/ramsayleung/rspotify/tree/v0.9/src/blocking[`blocking` module
in Rspotify]. Since the `reqwest` and `reqwest::blocking` clients share the same
interface, manually removing `async`/`.await` and importing `reqwest::blocking`
instead in the new module will work without much complexity overhead.

The Rspotify user just has to import `rspotify::blocking::Client` instead of
`rspotify::Client`, and voilà! Their code is now blocking. And if we don't want
overhead for the async users we can just feature-gate it under the name
`blocking` and done.

The problem was much more clear later on, though. Half the crate's code was
duplicated. Adding a new endpoint or modifying it meant writing or removing
everything twice. And good luck if you had to refactor something, prepare
yourself to double your efforts!

There is no way to make sure both implementations are equivalent either unless
you test absolutely everything. Which isn't a bad idea either, but maybe you
copy pasted the tests wrong! How about that? The poor reviewer of the Pull
Request would have to read through the same code twice as well to make sure both
sides look alright -- which sounds incredibly prone to human errors.

In my experience it really slowed down the development of Rspotify, specially
for new contributors who weren't used to this whole ordeal. And so as a new
excited maintainer of Rspotify, I began to
https://github.com/ramsayleung/rspotify/issues/112[investigate other possible
solutions].

=== Calling `block_on`

https://github.com/ramsayleung/rspotify/pull/120[Our second approach] consisted
on implementing everything in the async side. Then, you just make wrappers for
the blocking code calling
https://docs.rs/tokio/latest/tokio/runtime/struct.Runtime.html#method.block_on[`block_on`
internally]. `block_on` will run the future until completion, basically
converting it into blocking code. This way you need to copy the _definitions_,
and the implementation is written once only.

[source, rust]
----
mod blocking {
    struct Spotify(super::Spotify);

    impl Spotify {
        fn endpoint(&self, param: String) -> SpotifyResult<String> {
            runtime.block_on(async move {
                self.0.endpoint(param).await
            })
        }
    }
}
----

Note that in order to call `block_on`, you first have to create some kind of
runtime. For example, with {{< crate tokio >}}:

[source, rust]
----
let mut runtime = tokio::runtime::Builder::new()
    .basic_scheduler()
    .enable_all()
    .build()
    .unwrap();
----

This raises the question: should we initialize the runtime in each call to the
endpoint, or is there a way to share it? We could keep it as a global (_ewwww_)
or perhaps better we can save the runtime in the `Spotify` struct. But since it
takes a _mutable_ reference to the runtime, you'd have to wrap it up with
`Arc<Mutex<T>>`, completely killing the concurrency in your client. Instead, you
may use a Tokio
https://docs.rs/tokio/latest/tokio/runtime/struct.Handle.html[Handle], which
contains a reference to the runtime internally. One way to do it would be:

[source, rust]
----
use tokio::runtime::Runtime;

lazy_static! { // You can also use `once_cell`
    static ref RT: Runtime = Runtime::new().unwrap();
}

fn endpoint(&self, param: String) -> SpotifyResult<String> {
    RT.handle().block_on(async move {
        self.0.endpoint(param).await
    })
}
----

While this does make our blocking client faster <<block-on-perf>>, turns out
that we're just walking in circles. {{< crate reqwest >}} does it differently in
order to achieve even more performance. Without getting into nasty details, it
basically spawns a thread that calls `block_on` waiting on a channel with jobs
<<block-on-channels>> <<block-on-reqwest>>.

Unfortunately this has quite the overhead. You have to pull in `futures`,
`tokio`, etc, and include them in your binary in order to... actually end up
writing blocking code. So not only is it a cost at runtime, but also at compile
time. It just feels wrong to me.

And you still have a good amount of duplicate code. Mostly definitions, since
the implementation is only written in the async side, but still, there are _a
lot_ of definitions. {{< crate reqwest >}} is a huge project and can probably
afford this for their `blocking` module. But this doesn't really apply to
`rspotify`.

I wonder, is there something better than this?

=== Other ideas

Another possible way to fix this is, as the features docs suggest, creating
separate crates. We'd have `rspotify-sync` and `rspotify-async`, and users would
just pick whichever crate they want as a dependency, even both if they need to.
The problem is -- again -- how exactly do we generate both versions of the
crate? In this case we can't even use procedural macros because you can't just
create a new crate within a macro. We could define a file format with a specific
syntax and replace parts of the code like `async`/`.await` inside the
`build.rs`. But that sounds completely out of scope.

////
TODO: research https://github.com/bodil/im-rs
////

== What ended up "`working`": the `maybe_async` crate

https://github.com/ramsayleung/rspotify/pull/129[The third attempt] is based on
a crate called {{< crate maybe_async >}}. I remember thinking it was the perfect
solution back when I discovered it. I was so happy I had managed to solve this
issue. Hahaha.

Anyway, the idea is that with this crate you can automatically remove the
`async` and `.await` occurrences in your code with a procedural macro,
essentially automating the copy-pasting approach. For example:

[source, rust]
----
#[maybe_async::maybe_async]
async fn endpoint() { /* stuff */ }
----

Generates the following code:

[source, rust]
----
#[cfg(not(feature = "is_sync"))]
async fn endpoint() { /* stuff */ }

#[cfg(feature = "is_sync")]
fn endpoint() { /* stuff with `.await` removed */ }
----

You can configure whether you want asynchronous or blocking code by toggling the
`maybe_async/is_sync` feature when compiling the crate. The macro works for
functions, traits and `impl` blocks. If needed, you can specify custom
async/sync implementations with the `async_impl` and `sync_impl` procedural
macros, respectively. It does its job perfectly, and we've been using it for
Rspotify for a while now with no problems whatsoever.

In fact, it worked so well that what I made Rspotify _http-client agnostic_,
which is even more flexible than being _async/sync agnostic_. This allowed us to
support multiple HTTP clients like {{< crate reqwest >}} and {{< crate ureq >}},
independently of whether the client is asynchronous or synchronous.

////
TODO: research crates which are async runtime agnostic

"More or less like how some crates support multiple async backends (say {{<
crate tokio >}} and {{< crate async_std >}})"

^ Maybe it's `smol` instead of `async_std`
////

This is not that hard to implement if you have `maybe_async` around. You just
need to define a trait for the
https://github.com/ramsayleung/rspotify/blob/89b37219a2230cdcf08c4cfd2ebe46d64902f03d/rspotify-http/src/common.rs#L46[HTTP
client], and then implement it for each of the clients you want to support
(https://github.com/ramsayleung/rspotify/blob/89b37219a2230cdcf08c4cfd2ebe46d64902f03d/rspotify-http/src/reqwest.rs#L97[1],
https://github.com/ramsayleung/rspotify/blob/89b37219a2230cdcf08c4cfd2ebe46d64902f03d/rspotify-http/src/ureq.rs#L56[2]).
Then, the user may configure whichever client they want to use with feature
flags in their `Cargo.toml`. For example, if `client-ureq` is enabled, since
`ureq` is synchronous, it would enable `maybe_async/is_sync` (removing
`async`/`.await`), and the Rspotify client would use ``ureq``'s implementation
internally.

This means that this solution has none of the downsides I listed in previous
attempts:

* No code duplication at all
* No overhead neither at runtime nor at compile time. If the user wants a
  blocking client, they can use `ureq`, which doesn't pull `tokio` and friends
* Quite easy to use; just configure a flag in you `Cargo.toml`

However, stop reading for a couple minutes and try to figure out why you
shouldn't do this. In fact, I'll give you 9 months, which is how long it took me
to do so...

=== The problem

Well, the thing is that features in Rust must be *additive*: "`enabling a
feature should not disable functionality, and it should usually be safe to
enable any combination of features`". Cargo may merge features of a crate when
it's duplicated in the dependency tree in order to avoid compiling the same
crate multiple times.
https://doc.rust-lang.org/cargo/reference/features.html#feature-unification[The
reference explains this quite well, if you want more details].

This optimization means that mutually exclusive features may break a dependency
tree. In our case, if Cargo merges the features `client-ureq` and
`client-reqwest`, the user will get hit by a compiler error; `maybe_async` will
have generated both async and sync function signatures, which conflict. So you
can't have a crate that depends on both sync and async Rspotify directly or
indirectly; the whole concept of `maybe_async` is currently wrong according to
the Cargo reference.

=== The feature resolver v2

A common misconception is that this is fixed by the feature resolver v2, which
https://doc.rust-lang.org/cargo/reference/features.html#feature-resolver-version-2[the
reference also explains quite well]. It will be enabled by default in the 2021
edition, but you can currently specify it inside your `Cargo.toml`. This new
version, among other things, avoids unifying features in some special cases, but
not in ours:

____
* Features enabled on platform-specific dependencies for targets not currently
  being built are ignored.
* Build-dependencies and proc-macros do not share features with normal
  dependencies.
* Dev-dependencies do not activate features unless building a target that needs
  them (like tests or examples).
____

Just in case, I tried to reproduce this myself, and it did work as I expected.
https://github.com/marioortizmanero/resolver-v2-conflict[This repository] is an
example of conflicting features, which breaks with any feature resolver.

=== Other fails

There are a a few crates that have this problem currently:

* {{< crate arangors >}} and {{< crate aragog >}}: wrappers for ArangoDB. Both
  use `maybe_async` to switch between async and sync (``arangors``'s author is
  the same, in fact) <<arangors-error>> <<aragog-error>>.
* {{< crate inkwell >}}: a wrapper for LLVM. It supports multiple versions of
  LLVM, which are not compatible with eachother <<inkwell-error>>.
* {{< crate k8s-openapi >}}: a wrapper for Kubernetes, with the same issue as
  `inkwell` <<k8s-error>>.

These crates do warn that they have  

=== Fixing `maybe_async`

Once more people became aware of this problem,
https://github.com/fMeow/maybe-async-rs/issues/6[this issue was opened in
`maybe_async`], which basically explains the situation and tries to provide a
fix. It's actually not that complicated; `maybe_async` would generate the
functions in the same way, but with a `_sync` or `_async` suffix appended to the
identifier. That way they wouldn't be conflicting. For example:

[source, rust]
----
#[maybe_async::maybe_async]
async fn endpoint() { /* stuff */ }
----

Would now generate the following code:

[source, rust]
----
#[cfg(feature = "is_async")]
async fn endpoint_async() { /* stuff */ }

#[cfg(feature = "is_sync")]
fn endpoint_sync() { /* stuff with `.await` removed */ }
----

In my opinion, however, the user experience will suck if these suffixes have to
be added to each call to your library. I wondered if it would be possible to do
it in a more ergonomic way. I forked `maybe_async` and gave it a try, about
which you can read more
https://github.com/fMeow/maybe-async-rs/issues/6#issuecomment-880581551[in this
series of comments]. But in summary it was very complicated and I ultimately
gave up.

The only way to fix this edge case would be to considerably worsen the usability
of Rspotify for everyone. Someone depending on both async and sync is a minority
and not that important, I think. Unlike `reqwest`, `rspotify` is a "`high
level`" library, so it's unlikely that it appears more than once in a dependency
tree in the first place. Perhaps we could ask the Cargo devs for help?

=== Support from Cargo

Rspotify is far from being the first who has been through this problem, so there
has been some discussion about it already:

* https://github.com/rust-lang/rfcs/pull/2962[This RFC for the Rust compiler]
  suggested adding the `oneof` configuration predicate (think `#[cfg(any(...))]`
  and similars) to support exclusive features. This only makes it easier to have
  conflicting features for cases where there's no choice, but features should
  still be strictly additive.
* The previous RFC started
  https://internals.rust-lang.org/t/pre-rfc-cargo-mutually-exclusive-features/13182/27[some
  discussion] in the context of allowing exclusive features in Cargo itself, and
  although it has some interesting info, it didn't go too far.
* https://github.com/rust-lang/cargo/issues/2980[This issue in Cargo] explains
  how additive features are impossible for the Windows API. The discussion
  includes more examples and ideas for a solution.
* https://github.com/rust-lang/cargo/issues/4803[Another issue in Cargo] asks
  for a way to test/build with combinations of flags easily. If features are
  strictly additive, then `cargo test --all-features` will cover everything. But
  in case it doesn't, the user has to run the command with multiple combinations
  of feature flags, which is quite cumbersome. This is already possible
  unofficially thanks to https://github.com/taiki-e/cargo-hack[`cargo-hack`].

According to
https://github.com/rust-lang/rfcs/pull/2962#issuecomment-664656377[this
comment], it's not something the Rust team has already discarded; it's still
being discussed. But these threads are relatively recent, so there hasn't been
much progress yet.

== Conclusion

I know, this is a problem that I've imposed to myself. We could just say "`No. We
only support async`" or "`No. We only support sync`". While there are users
interested in being able to use both, sometimes you just have to say no. If such
a feature becomes so complicated to deal with that your entire codebase becomes
a mess, and you don't have the enough engineering power to maintain it, then
it's your only choice.

Most API wrappers and the like only support either asynchronous or blocking
code. {{< crate serenity >}} (Discord API), {{< crate sqlx >}} (SQL toolkit) and
{{< crate teloxide >}} (Telegram API) are async-only, for example.

This means that I'm seriously considering just dropping support for both sync
and async code. It's just become a mess that we don't have the manpower to deal
with. The problem is that some crates that depend on rspotify like
https://github.com/hrkfdn/ncspot[`ncspot`] or
https://github.com/Spotifyd/spotifyd[`spotifyd`] are blocking, and others like
https://github.com/Rigellute/spotify-tui[`spotify-tui`] use async, so I'm not
sure what they'd think.

Even though it was quite frustrating at times, I don't really regret spending so
much time walking on circles. I was contributing to Rspotify in the first place
just to _learn_. I had no deadlines, and no stress, I just wanted to try to
improve a library in Rust in my free time. And I _have_ learned a lot; hopefully
you too, after reading this.

[bibliography]
== References

- [[[block-on-perf,     1]]] https://github.com/ramsayleung/rspotify/issues/112#issuecomment-683266508
- [[[block-on-channels, 2]]] https://github.com/seanmonstar/reqwest/blob/0.10.x/src/blocking/client.rs#L757
- [[[block-on-reqwest,  3]]] https://github.com/ramsayleung/rspotify/issues/112#issuecomment-683249563
- [[[features-additive, 4]]] https://github.com/rust-lang/cargo/blob/master/src/doc/src/reference/features.md#feature-unification
- [[[arangors-error,    5]]] https://github.com/SergioBenitez/Rocket/pull/1433
- [[[aragog-error,      6]]] https://gitlab.com/qonfucius/aragog/-/blob/0.140.0/src/lib.rs#L488
- [[[inkwell-error,     7]]] https://github.com/TheDan64/inkwell/blob/bfb0e32bc329fd35f6c5a529a1a6209936a147f8/src/lib.rs#L107
- [[[k8s-error,         8]]] https://github.com/Arnavion/k8s-openapi/blob/v0.13.0/build.rs#L31
