---
title: "Plugins in Rust: Preparing for Deployment"
description: "The last finishing touches to the plugin system so that it can be
released in Tremor's new version"
author: "Mario Ortiz Manero"
tags: ["rust", "rustlang", "plugin", "benchmarking", "testing", "deployment"]
series: ["rust-plugins"]
date: 2021-11-09
GHissueID: TODO
---

:sectnums:
:stem: latexmath

:repr-c: pass:quotes[`#[repr\(C)]`]
:work: pass:quotes["`just make it work`"]

////
I even hit a bug in the compiler, which made me feel oddly proud:

(include image)

It's seemingly related to incremental compilation and already reported:

https://github.com/rust-lang/rust/issues/90608
////

== Benchmarking process

Benchmarking procedure

Important:

* Make sure everything heavy is closed: discord, firefox, neovim + lsp, etc
* Histograms: https://hdrhistogram.github.io/HdrHistogram/plotFiles.html

.benchmark
[source]
----
cd tremor-cli/tests/bench/passthrough
export TREMOR_PATH=../../../../tremor-script/lib:../../lib/
../../../../target/release/tremor test bench . >
~/Programming/nullderef.com/content/blog/plugin-end/results/NAME.hgrm
----

.or for flamegraph
[source]
----
flamegraph ../../../../target/release/tremor test bench . > ~/Programming/nullderef.com/content/blog/plugin-end/results/NAME.hgrm
----

== Results

* Throughput was reduced 35% initially
* Latency had also been affected considerably at every percentile (TODO insert
  histogram here)
* According to the flamegraph 7% of the execution time was just conversions
  between regular and PDK types (TODO insert screenshot with search)

Lastly, I've found it especially rewarding to do all of this in an open source
environment. Even if you're working for a company with propietary software,
please try to contribute upstream instead of forking or patching. Try to be nice
to those who are saving you so much work, and submit a PR or an issue:

// TODO: use github shortcode
.Most of my contributions while implementing the PDK
* https://github.com/oxalica/async-ffi/pull/10
* https://github.com/oxalica/async-ffi/pull/11
* https://github.com/rodrimati1992/abi_stable_crates/pull/58
* https://github.com/rodrimati1992/abi_stable_crates/pull/59
* https://github.com/rodrimati1992/abi_stable_crates/pull/61
* https://github.com/rodrimati1992/abi_stable_crates/pull/68
* https://github.com/rodrimati1992/abi_stable_crates/pull/70
* https://github.com/rodrimati1992/abi_stable_crates/pull/74
* https://github.com/simd-lite/simd-json-derive/pull/9
* https://github.com/simd-lite/value-trait/pull/14
* https://github.com/simd-lite/value-trait/pull/16
* https://github.com/simd-lite/value-trait/pull/18

[bibliography]
== References

- [[[empty,      1]]] http://google.com
