---
title: "Surprised by Rust's Subtyping and Variance"
description: "TODO"
author: "Mario Ortiz Manero"
images: ["TODO"]
tags: ["tech", "programming", "rust", "rustlang", "variance", "subtyping", "abi_stable"]
date: 2022-01-29
GHissueID: TODO
draft: true
---

:sectnums:
:stem: latexmath

:repr-c: pass:quotes[`#[repr\(C)]`]
:repr-rust: pass:quotes[`#[repr(Rust)]`]
:work: pass:quotes["`just make it work`"]
:heinz: https://twitter.com/heinz_gies/[Heinz]

// Sources:
// https://doc.rust-lang.org/nomicon/subtyping.html
// https://lcnr.de/blog/diving-deep-implied-bounds-and-variance/

_Subtyping and variance_ is something that works in the background, making your
life easier without you even knowing about it. That is, until it starts making
your life harder instead. It might be a good idea to know its pitfalls in order
to know when you are running into these unlikely issues.

This topic isn't covered in the https://doc.rust-lang.org/book/[The Rust Book].
We'll only find it in its more obscure, unsafer brother,
https://doc.rust-lang.org/nomicon[The Rustonomicon]. It's actually incredibly
well explained in there, so I will refrain from repeating myself. If you want to
know more details, I would strongly recommend you to check out yourself the
following sources, as this will only cover part of the topic.

. https://doc.rust-lang.org/nomicon/subtyping.html["`Subtyping and Variance`" --
  The Rustonomicon]
. https://doc.rust-lang.org/reference/subtyping.html["`Subtyping and Variance`"
  -- The Rust Reference]
. https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)["`Covariance
  and contravariance`" -- Wikipedia]

There's also a couple blog posts with a more practical approach, like
https://medium.com/@orbitalK/rust-lifetime-subtype-variance-b58434fe36ed["`Rust
Lifetime Subtype Variance`" -- Prolific K] or
https://lcnr.de/blog/diving-deep-implied-bounds-and-variance/["`Diving Deep:
implied bounds and variance`" -- lcnr.de]. If you're more of a visual learner,
then https://www.youtube.com/watch?v=iVYWDIW71jk[this video from Jon Gjengset]
might be best for you.

Furthermore, this article may be unnecessarily verbose if you're _just_ trying
to learn about subtyping and variance. That's because I also wanted to cover the
steps I took to solve the issue. Specifically, I sometimes run into lifetime
issues that I don't even know how to approach. This is one of these cases, and I
think I learned quite a few important lessons.

== The problem

As part of my https://nullderef.com/series/rust-plugins/[Plugin System in Rust]
series, I was making one of Tremor's core types FFI-compatible (a.k.a.
{repr-c}). I was using the crate {{< crate abi_stable >}}, which includes
re-implementations of the standard library that are {repr-c} for this exact
purpose. Thanks to it, the task should be as easy as changing the `std` types in
my enum with theirs -- theoretically.

.Before (simplified)
[source, rust]
----
pub enum Value {
    String(String),
    Array(Vec<Value>),
    Object(Box<HashMap<String, Value>>),
    Bytes(Vec<u8>),
}
----

.After (simplified)
[source, rust]
----
use abi_stable::std_types::{RString, RVec, RBox, RHashMap};

#[repr(C)]
pub enum Value {
    String(RString),
    Array(RVec<Value>),
    Object(RBox<RHashMap<RString, Value>>),
    Bytes(RVec<u8>),
}
----

Naturally, this brought up lots of compilation errors; the `Value` type was used
a lot in the codebase, and its usage had changed. For whatever reason, some of
these errors were related to lifetimes, and I didn't really know what was wrong.
I chose to ignore these until the end and I spent the following hours fixing the
simplest errors.

However, after being done with these, I was left with over 70 errors related to
lifetimes. I still had absolutely no idea how to even approach them because they
made no sense at all:

// TODO picture or code snippet

Now, this doesn't necessarily have to happen to you in the same context as mine.

== Debugging the issue

{heinz}, my mentor, managed to reproduce the issue:

[source, rust]
----
use abi_stable::std_types::RCow;
use std::borrow::Cow;

fn cmp_cow<'a, 'b>(left: &Cow<'a, ()>, right: &Cow<'b, ()>) -> bool {
    left == right
}

// This will fail to compile
fn cmp_rcow<'a, 'b>(left: &RCow<'a, ()>, right: &RCow<'b, ()>) -> bool {
    left == right
}
----

With the following error, again:

[source]
----
$ cargo b
   Compiling repro v0.1.0 (/home/mario/Downloads/repro)
error[E0623]: lifetime mismatch
  --> src/lib.rs:10:10
   |
9  | fn cmp_rcow<'a, 'b>(left: &RCow<'a, ()>, right: &RCow<'b, ()>) -> bool {
   |                            ------------          ------------
   |                            |
   |                            these two types are declared with different lifetimes...
10 |     left == right
   |          ^^ ...but data from `left` flows into `right` here

For more information about this error, try `rustc --explain E0623`.
error: could not compile `repro` due to previous error
----

At first sight, ``RCow``'s implementation of `PartialOrd` was the same as
`Cow`'s:

.RCow
[source, rust]
----
impl<'a, B> PartialOrd<RCow<'a, B>> for RCow<'a, B>
where
    B: PartialOrd + BorrowOwned<'a> + ?Sized,
{
    #[inline]
    fn partial_cmp(&self, other: &RCow<'a, B>) -> Option<Ordering> {
        PartialOrd::partial_cmp(&**self, &**other)
    }
}
----

.Cow
[source, rust]
----
impl<'a, B: ?Sized> PartialOrd for Cow<'a, B>
where
    B: PartialOrd + ToOwned,
{
    #[inline]
    fn partial_cmp(&self, other: &Cow<'a, B>) -> Option<Ordering> {
        PartialOrd::partial_cmp(&**self, &**other)
    }
}
----

== Trying to fix it

I first fixed the PartialEq implementation by making it explicit that I want to
be able to compare new lifetimes:

.Before
[source, rust]
----
impl<'a, B> PartialEq<RCow<'a, B>> for RCow<'a, B>
where
    B: PartialEq + BorrowOwned<'a> + ?Sized,
{
    fn eq(&self, other: &RCow<'a, B>) -> bool {
        PartialEq::eq(&**self, &**other)
    }
}
----

.After
[source, rust]
----
impl<'a, 'b, B, C> PartialEq<RCow<'b, C>> for RCow<'a, B>
where
    B: PartialEq<C> + BorrowOwned<'a> + ?Sized,
    C: BorrowOwned<'b> + ?Sized,
{
    fn eq(&self, other: &RCow<'b, C>) -> bool {
        PartialEq::eq(&**self, &**other)
    }
}
----

Then, I created an equivalent example and tried to compile it:

[source, rust]
----
use abi_stable::std_types::RCow;
use std::borrow::Cow;

fn cmp_cow<'a, 'b>(left: &Cow<'a, ()>, right: &Cow<'b, ()>) -> bool {
    left.eq(right)
}

fn cmp_rcow<'a, 'b>(left: &RCow<'a, ()>, right: &RCow<'b, ()>) -> bool {
    left.eq(right)
}
----

Thanks to that, it now compiled! Time for `PartialOrd` (I had to do `PartialEq`
first because `PartialOrd` requires it):

[source, rust]
----
----

Possible fixes:

=== Removing the trait that binds the lifetime
=== GATs?
=== The scary `transmute`

{heinz}'s idea:

[source, rust]
----
struct SCow<'a>(RCow<'a, ()>);
impl<'a, 'b> PartialEq<SCow<'a>> for SCow<'b> {
    fn eq(&self, other: &SCow<'a>) -> bool {
        unsafe {
            let other0: &RCow<'b, ()> = std::mem::transmute(&other.0);
            &self.0 == other0
        }
    }
}
----

This will actually work now:

[source, rust]
----
fn cmp_cow<'a, 'b>(left: &Cow<'a, ()>, right: &Cow<'b, ()>) -> bool {
    left == right
}
fn cmp_scow<'a, 'b>(left: &SCow<'a>, right: &SCow<'b>) -> bool {
    left == right
}
----

== The final solution

[.text-center]
{{< gh issue "rodrimati1992/abi_stable_crates" 75 "lifetimes with R* types break compared to non R* types" "paragraph" >}}

== Conclusion

I would honestly say that the fact it took me so long to realize the error is
Rust's fault. There were no indications in the errors about variance. I
understand that there were 

Thanks a lot to {heinz} for the TODO help in this issue!
