---
title: "Aroa, I wish I could tell you how f*cking cool you are"
description: "TODO"
author: "Mario Ortiz Manero"
images: ["TODO"]
tags: [TODO]
date: 2024-01-14
GHissueID: TODO
draft: true
---

{{< viz3d-setup >}}

Today, I want to convince you of how admirable my sister, Aroa, was.

{{< viz3d
      src="/blog/aroa/art/3d/test.glb"
      poster="/blog/aroa/art/3d/test-poster.webp"
      alt="Test file"
>}}

// == What I've learned

I've always learned so much from my sister, especially because of how different
we were. For one, she gave absolutely no fucks. You could see her with the
weirdest clothing combinations that yet made her look fabulous. TODO with TODO?
Slashing. TODO with TODO? Cool as hell. Her expressions, her personality... She
was like a pink dense cloud that absorbed and impressed everyone.

TODO: picture of cool outfit

What sucks is that she surely wasn't aware of how cool she was. Her artistic
skills were amazing, particularly when she started to do 3D paintings. For
example, here she cut off pictures from a magazine and glued more things on top:

TODO: picture in the office

She always had a hard time finding a purpose or a career that would fit her. It
was astronomy for a bit, and she even tried a semester of Geology. She signed up
for an automotive workshop and later gave content creation a try for CBD
companies. We built her CV together, and I gifted her a digital pencil to use it
to draw and take notes.

Her artistic talents were amazing, but she never pursued them. Painting
definitely helped to go through TLP, though.

My sister gave me a good lesson: people are more than what they work for. It's
important to try to find fulfillment outside of it. Explore themselves, learn,
create. Yes, I moved to Munich because of work. But also because of it, I
stopped writing on my blog. I also didn't try to learn German for some time
because I thought it would be too much. I was okay in the sense that I was
having fun in life, and I was still learning. But it feels like a different kind
of learning, where you learn about concepts and experiences but not about
yourself and what you like. Make sure you have unproductiveness in every day of
your life and to embrace boredom when possible.

== How was it?

My mother called me to tell me the news. The timing was extraordinary, as I was
a few minutes away from a flight taking off. My world fell apart, and I couldn't
stop crying. The flight attendants were very nice and took me to their reserved
row at the front to calm my nerves. After crying for so long, they became
worried I'd dehydrate or that it'd turn into a panic attack. So they asked me to
take a tranquilizer... as a rectal suppository. For flight reasons, I suppose.
I'm sure Aroa would have gotten a huuuge kick out of that. Man, I know she's
still laughing somewhere.

Being stuck for 4 hours in a flight, I thought of all the things that can be
thought, and I felt all the feelings that can be felt.

When I reunited with my family, I guess I couldn't assume what had happened.
What I could definitely see, is how completely broken my loved ones were.
Instinctively, I worried more for others than for myself at the beginning.

One particularly shocking part was the physical reaction -- I didn't know the
concept of "https://en.wikipedia.org/wiki/Somatization[somatization]". When I
was told about it in the airplane, my arms literally went numb for several
minutes. It was completely disconcerting and alarming. After a couple of weeks,
my physical strength took a nosedive. I got sick and experienced some of the
worst back cramps of my life; I couldn't even leave bed for two days straight. I
slowly improved, but continued to be exhausted for weeks. Mentally, I was
prepared to go swim for kilometers, but my body wasn't able to; it was very
frustrating, and also unkown to me.

For a long time, I had thought about changing jobs. Almost a year later, I
actually quit my job at Lyft with amazing colleagues and good opportunities
ahead. It was an extremely hard decision, but I'm hoping that will bring more
meaning into my life. And if it doesn't, it's a good thing I'm still young to do
stupid things.

==== Therapy

I always thought therapy was just sitting in a white neat room with someone
asking you questions. And while the questions part remains true, I've found that
the environment in which they are asked is essential to make it work. Some can
find more comfort in sharing a beer with a laid-back therapist, while others can
open up easily in nature or among horses.

Talking with your patients in a bar sounds bad, but if that's the only way to
have them stick to it, then it's better than nothing. I'm not sure how frowned
upon it is in the field, but I hope it's more normalized, and that we see more
adaptive methods.

At the beginning, therapy may seem to make things worse. It's like getting all
the shit outside and mixing it together. It stinks and makes you cry.

My sister always had trouble sticking to therapy. She was let down by a
deficient healthcare system that has much to work on.

// ===== Care

// A surprising amount of urgent-care therapists showed a lack of care.
// Gut-wrenching stories of her being stuck for hours in a waiting room with
// suicidal intentions and screams.

// Importantly, this lack of care wasn't only towards the patient, but also for the
// family. None of us had absolutely any idea what we were getting into. Learning
// more about what she was going through was like trying to squeeze a drop of
// water from an empty bottle. No expectations whatsoever of how severe it was, nor
// indications of how to handle this at home.

// Even if the patient goes to therapy, most of their time is spent at home.

[bibliography]
== References

[.text-left]
- [[[physics-guy, 1]]] https://www.youtube.com/watch?v=a83ZJ18u6kg[i studied
  physics in college — now i'm unemployed and living alone in the desert lol
  what happened? -- YouTube, Alex Wei]
- [[[neuroscience-guy, 2]]] https://www.youtube.com/watch?v=25LUF8GmbFU[I Was An
  MIT Educated Neurosurgeon Now I'm Unemployed And Alone In The Mountains How
  Did I Get Here? -- YouTube, Goobie and Doobie]
- https://en.m.wikipedia.org/wiki/Copycat_suicide
- https://news.ycombinator.com/item?id=38935605
- https://www.fortressofdoors.com/i-lost-my-son/
- https://news.ycombinator.com/item?id=40521963
