---
title: "Aroa, I wish I could tell you how f*cking cool you are"
description: "TODO"
author: "Mario Ortiz Manero"
images: ["TODO"]
tags: [TODO]
date: 2024-01-14
GHissueID: TODO
draft: true
---

== What I've learned

I recently heard a phrase from NVIDIA's founder Jen-Hsun Huang which struck with
me: "you need to be able to learn from everyone, even children". I think this is
particularly interesting with your family. You don't get to choose your family,
which means that what you get is completely random. If someone has a personality
that doesn't match with you, or some aspects that you dislike, you can simply
not be their friend. But unless it's harmful or excessive, you can't do the same
with your family. You have to learn to live with things that you just didn't
choose.

And I've always learned a lot with her.

=== Work doesn't define you

One of the sources of distress in my sister was a lack of purpose. She seemed to
have fun in the short run, but didn't quite have plans for the counterpart.
Being a waitress was a middle step for her, but at the same time she didn't know
what that step after would be.

She was extremely strong to try many things, because she couldn't find a
'undeniable' passion. It was astronomy for a bit, and she even tried a semester
of Geology. She signed up for an automotive worshop and even gave content
creation a try for CBD companies.

I believed I was able to help in this regard. We built her CV together, and I
gifted her a digital pencil to use it to draw and take notes. Sometimes, I asked
her about what she could pursue as a career to feel fulfilled, trying to get
something out of her.

I kind of wish she had embraced her artistic side more. Maybe that would've
helped. Who knows.

My point is that people are just very different with respect to work. It surely
is what pays the bills and gets you going many times. But it's too easy for me
to get caught in that. People are more than what they work for; it's important
to try to find fulfillment outside of it if possible. Explore themselves, learn,
create.

Yes, I moved to Munich because of work. But also because of it, I had stopped
writing on my blog. I also didn't try to learn German for some time because I
thought it would be too much. I was okay in the sense that I was having fun in
life, and I was still learning. But it feels like a different kind of learning,
where you learn about concepts and experiences but not about yourself and what
you like.

=== About mental health

It sucks so very much how little the public knows about this. I wish you didn't
have to go through problems with mental health in order to learn about it. Which
is how I think it works currently. Ideally, noone should know about it because
it shouldn't happen to them. But it _will_ happen, even if not to you, to
someone else. And knowing about it will make you comprehend them better and care
for that person more.

One particularly shocking part was the physical one. When I was told about it in
the airplane, my arms literally went numb. It was completely disconcerting and
unexpected to me. Similarly, I didn't know the concept of "somatization". After
a couple of weeks, my physical strength took a nosedive. I got sick and then
experienced some of the worst back cramps of my life; I couldn't even leave bed
for two days straight. I slowly improved, yet still felt extremely tired for
weeks. Mentally, I was prepared to go swim for kilometers, but my body wasn't
able to; it was very frustrating, and also unkown to me.

== References

* https://en.m.wikipedia.org/wiki/Copycat_suicide
* https://news.ycombinator.com/item?id=38935605
* https://www.fortressofdoors.com/i-lost-my-son/
